import React, { createContext, useContext, useState, useCallback, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About Us',
    'nav.services': 'Services',
    'nav.doctors': 'Find a Doctor',
    'nav.patients': 'Patients',
    'nav.research': 'Research',
    'nav.contact': 'Contact Us',
    'nav.resources': 'Resources',
    'nav.more': 'More',
    'nav.facilities': 'Facilities',
    'nav.medicalTourism': 'Medical Tourism',
    'nav.partnerships': 'Partnerships',
    'nav.developmentPhases': 'Development Phases',
    'nav.investment': 'Investment',
    'nav.insurance': 'Insurance & Billing',
    'nav.news': 'News',
    'nav.careers': 'Careers',
    'nav.location': 'Location',
    'nav.faq': 'FAQ',
    'nav.patientPortal': 'Patient Portal',

    // Hero
    'hero.title': 'CAPITALMED',
    'hero.tagline': 'Trusted for Life',
    'hero.description': "Egypt's premier smart healthcare city, delivering world-class medical excellence across 144 acres in New Cairo.",
    'hero.stats.area': '577,000 m²',
    'hero.stats.investment': '$1.2B',
    'hero.stats.beds': '4,500+ Beds',
    'hero.stats.specialties': '100+ Medical Specialties',
    'hero.stat.campusArea': 'Campus Area',
    'hero.stat.investment': 'Investment',
    'hero.cta.doctor': 'Find a Doctor',
    'hero.cta.learn': 'Learn More',
    'hero.smartCity': 'Smart Healthcare City',
    'hero.laPlaza': 'La Plaza Hospital',
    'hero.laPlaza.tagline': 'A CAPITALMED Hospital',

    // Quick Access Bar
    'quick.bar.patients': 'Patients',
    'quick.bar.doctors': 'Doctors',
    'quick.bar.bookNow': 'Book Now',
    'quick.bar.emergency': 'Emergency',
    'quick.bar.hotline': 'Hotline',

    // Quick Actions
    'quick.title': 'You may be looking for',
    'quick.doctor': 'Find a Doctor',
    'quick.doctor.desc': 'Search for a specialist',
    'quick.doctor.cta': 'Search Now',
    'quick.appointments': 'Appointments',
    'quick.appointments.desc': 'Book a visit online',
    'quick.appointments.cta': 'Book Now',
    'quick.facilities': 'Our Facilities',
    'quick.facilities.desc': 'View our departments',
    'quick.facilities.cta': 'Explore',
    'quick.specializations': 'Specializations',
    'quick.specializations.desc': 'Explore our expertise',
    'quick.specializations.cta': 'Learn More',
    'quick.tourism': 'Medical Tourism',
    'quick.tourism.desc': 'Plan your treatment abroad',
    'quick.tourism.cta': 'Get in Touch',
    'quick.contact': 'Contact Us',

    // Stats
    'stats.patients': 'Patients Annually',
    'stats.beds': 'Hospital Beds',
    'stats.icu': 'ICU Beds',
    'stats.operating': 'Operating Rooms',
    'stats.providers': 'Healthcare Providers',
    'stats.specialties': 'Medical Specialties',

    // Services
    'services.title': 'Our Solutions',
    'services.subtitle': 'Comprehensive Healthcare Services',
    'services.description': 'State-of-the-art medical facilities with international standards',
    'services.page.title': 'Our Medical Services',
    'services.page.subtitle': 'World-class healthcare services powered by cutting-edge technology and compassionate care',
    'services.learn.more': 'Learn More',
    'services.cardiology.title': 'Cardiology',
    'services.cardiology.desc': 'Comprehensive heart care from prevention to intervention',
    'services.neurology.title': 'Neurology',
    'services.neurology.desc': 'Expert care for brain and nervous system disorders',
    'services.orthopedics.title': 'Orthopedics',
    'services.orthopedics.desc': 'Advanced bone and joint care with minimally invasive techniques',
    'services.pediatrics.title': 'Pediatrics',
    'services.pediatrics.desc': 'Specialized care for children of all ages',
    'services.oncology.title': 'Oncology',
    'services.oncology.desc': 'Advanced cancer treatment with personalized care plans',
    'services.ophthalmology.title': 'Ophthalmology',
    'services.ophthalmology.desc': 'Complete eye care from routine exams to complex surgeries',
    'services.internal.title': 'Internal Medicine',
    'services.internal.desc': 'Comprehensive diagnosis and treatment of adult diseases',
    'services.surgery.title': 'Advanced Surgery',
    'services.surgery.desc': 'Cutting-edge surgical procedures with minimally invasive techniques',
    'services.emergency.title': '24/7 Emergency Care',
    'services.emergency.desc': 'Round-the-clock emergency services with rapid response teams ready to handle any medical emergency',
    'services.emergency.24/7': '24/7 Availability',
    'services.emergency.trauma': 'Level I Trauma Center',
    'services.emergency.ambulance': 'Advanced Ambulance Fleet',
    'services.emergency.rapid': 'Rapid Response Teams',
    'services.emergency.call': 'Call Emergency: 16999',
    'services.laboratory.title': 'Laboratory',
    'services.laboratory.desc': 'State-of-the-art diagnostic testing and analysis',
    'services.pharmacy.title': 'Pharmacy',
    'services.pharmacy.desc': '24/7 pharmacy services with comprehensive medication management',
    'services.ent.title': 'ENT',
    'services.ent.desc': 'Expert care for ear, nose, and throat conditions',
    'services.nutrition.title': 'Clinical Nutrition',
    'services.nutrition.desc': 'Personalized dietary plans and nutritional therapy for optimal health outcomes',
    'services.cta.title': 'Need Medical Assistance?',
    'services.cta.subtitle': 'Our team of experts is here to help you 24/7',
    'services.cta.appointment': 'Book Appointment',
    'services.cta.contact': 'Contact Us',

    // About
    'about.title': 'About CAPITALMED',
    'about.subtitle': 'Excellence in Healthcare',
    'about.description': 'CAPITALMED Healthcare City is a visionary project stretching over 144 acres in Badr City, New Cairo. With a total investment of over $1.2 billion USD, it is the largest integrated healthcare city in Africa and the Middle East, designed to serve over 5 million clients annually.',
    'about.page.title': 'About Us',
    'about.page.subtitle': 'Transforming healthcare delivery in Egypt, Africa, and the Middle East',
    'about.story.title': 'Our Story',
    'about.story.p1': 'CAPITALMED Healthcare City is a visionary project designed to transform healthcare delivery in Egypt, Africa, and the Middle East. Our state-of-the-art facilities combine cutting-edge technology with compassionate care.',
    'about.story.p2': 'Located in Badr City, New Cairo, we are building a comprehensive medical ecosystem comprising 19 fully integrated facilities that will serve millions of patients annually with world-class healthcare services.',
    'about.years': 'Years of Excellence',
    'about.mission': 'Our Mission',
    'about.mission.text': 'To provide accessible, high-quality healthcare services that improve lives and advance medical science across the region.',
    'about.vision': 'Our Vision',
    'about.vision.text': 'To be recognized as a regional premier destination for providing integrated world-class health care services to the community it serves in a safe, efficient, and respectful manner locally & internationally.',
    'about.values.title': 'Our Core Values',
    'about.values.subtitle': 'The principles that guide everything we do',
    'about.value.compassion': 'Compassion',
    'about.value.excellence': 'Excellence',
    'about.value.teamwork': 'Teamwork',
    'about.value.integrity': 'Integrity',
    'about.timeline.title': 'Our Journey',
    'about.milestone.1': 'Project announcement and groundbreaking ceremony',
    'about.milestone.2': 'Phase 1 construction completed',
    'about.milestone.3': 'First hospital wing opened to patients',
    'about.milestone.4': 'Full operation with all facilities active',
    'about.stat.area': 'Square Meters',
    'about.stat.providers': 'Healthcare Providers',
    'about.stat.patients': 'Patients Annually',
    'about.stat.specialties': 'Medical Specialties',

    // Doctors
    'doctors.page.title': 'Find a Doctor',
    'doctors.page.subtitle': 'Connect with our world-class medical professionals',
    'doctors.search.placeholder': 'Search by name or specialty...',
    'doctors.results': 'Showing {count} doctors',
    'doctors.experience': '{years} years experience',
    'doctors.book': 'Book',
    'doctors.no.results': 'No doctors found matching your criteria',

    // Contact
    'contact.title': 'Contact Us',
    'contact.subtitle': 'We are here to help',
    'contact.page.title': 'Contact Us',
    'contact.page.subtitle': "We're here to answer your questions and provide the care you need",
    'contact.address': 'Badr City, New Cairo, Egypt',
    'contact.phone': '+20 2 1234 5678',
    'contact.email': 'info@capitalmed.eg',
    'contact.hours': '24/7 Emergency Services',
    'contact.info.address': 'Address',
    'contact.info.phone': 'Phone',
    'contact.info.email': 'Email',
    'contact.info.hours': 'Working Hours',
    'contact.form.title': 'Send us a Message',
    'contact.form.name': 'Full Name',
    'contact.form.email': 'Email Address',
    'contact.form.phone': 'Phone Number',
    'contact.form.subject': 'Subject',
    'contact.form.message': 'Your Message',
    'contact.form.submit': 'Send Message',
    'contact.form.success': 'Message sent successfully! We will contact you soon.',
    'contact.faq.title': 'Frequently Asked Questions',
    'contact.faq.subtitle': 'Quick answers to common questions',
    'contact.faq.q1': 'What are your visiting hours?',
    'contact.faq.a1': 'General visiting hours are from 10:00 AM to 8:00 PM. ICU visiting hours are limited to specific times.',
    'contact.faq.q2': 'How do I book an appointment?',
    'contact.faq.a2': 'You can book online through our website, call us at 16999, or visit the reception desk.',
    'contact.faq.q3': 'Do you accept international patients?',
    'contact.faq.a3': 'Yes, we have a dedicated medical tourism department to assist international patients.',
    'contact.faq.q4': 'What insurance do you accept?',
    'contact.faq.a4': 'We accept most major insurance providers. Please contact us for specific information.',

    // Footer
    'footer.description': "Egypt's premier smart healthcare city, providing world-class medical services across 144 acres.",
    'footer.quicklinks': 'Quick Links',
    'footer.services': 'Services',
    'footer.contact': 'Contact',
    'footer.copyright': '© 2026 CAPITALMED Healthcare City. All Rights Reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',

    // Facilities
    'facilities.hero.label': 'World-Class Environment',
    'facilities.hero.title': 'Beyond Medicine',
    'facilities.hero.subtitle': 'A sanctuary for healing, designed with international standards of hospitality and comfort.',
    'facilities.hotel.label': 'Premium Hospitality',
    'facilities.hotel.title': 'The "Medical Hotel" Experience',
    'facilities.hotel.desc': 'We believe environment plays a crucial role in recovery. Our facility blends advanced medical care with the comfort of a luxury hotel.',
    'facilities.hotel.concierge': 'Concierge Services',
    'facilities.hotel.concierge.desc': 'Personalized assistance for travel, accommodation, and daily needs.',
    'facilities.hotel.suites': 'Executive Suites',
    'facilities.hotel.suites.desc': 'Private rooms with dedicated family areas and premium amenities.',
    'facilities.hotel.dining': 'Gourmet Dining',
    'facilities.hotel.dining.desc': 'In-room dining with menus curated by clinical nutritionists and chefs.',
    'facilities.retail.title': 'The Retail Promenade',
    'facilities.retail.subtitle': 'Convenience and lifestyle options right on campus',
    'facilities.retail.cafes': 'Cafés & Restaurants',
    'facilities.retail.shops': 'Shops & Essentials',
    'facilities.retail.bank': 'Bank & Services',
    'facilities.support.title': 'Visitor & Staff Support',
    'facilities.support.subtitle': 'Everything you need for a comfortable campus experience',
    'facilities.support.parking': 'Parking',
    'facilities.support.parking.desc': '2 basement levels with 2,000+ spaces and valet service',
    'facilities.support.wifi': 'Connectivity',
    'facilities.support.wifi.desc': 'Campus-wide high-speed Wi-Fi for patients and visitors',
    'facilities.support.lounge': 'Staff Lounges',
    'facilities.support.lounge.desc': 'Dedicated rest areas with dining facilities for staff',
    'facilities.support.green': 'Green Spaces',
    'facilities.support.green.desc': 'Healing gardens and outdoor walking paths throughout campus',

    // Medical Tourism
    'tourism.hero.label': 'The Global Nexus',
    'tourism.hero.title': 'World-Class Healthcare, Close to Home',
    'tourism.hero.subtitle': 'CapitalMed is the "Central Clinic of the World," accessible to 3.6 billion people within an 8-hour flight.',
    'tourism.packages': 'View Packages',
    'tourism.estimate': 'Estimate Cost',
    'tourism.why.title': 'Why Egypt?',
    'tourism.why.subtitle': 'Unmatched accessibility and value compared to global alternatives.',
    'tourism.why.europe': 'Europe',
    'tourism.why.gcc': 'GCC',
    'tourism.why.africa': 'Africa',
    'tourism.why.reach': 'Population within 8-hour reach',
    'tourism.packages.title': 'Choose Your Path',
    'tourism.packages.subtitle': 'Tailored packages for every need',
    'tourism.package.alacarte': 'À La Carte',
    'tourism.package.alacarte.sub': 'The Modular Path',
    'tourism.package.alacarte.price': 'Base Care + Add-ons',
    'tourism.package.doortodoor': 'Door-to-Door',
    'tourism.package.doortodoor.sub': 'The Concierge Path',
    'tourism.package.doortodoor.price': 'All-Inclusive Luxury',
    'tourism.popular': 'Most Popular',
    'tourism.premium.quote': 'Get Premium Quote',
    'tourism.customize': 'Customize Plan',
    'tourism.journey.title': 'Your Journey with Us',
    'tourism.journey.subtitle': 'A seamless timeline from inquiry to safe return.',
    'tourism.badge.icm': 'International Clinical Management',
    'tourism.hero.main.title': 'The Global Patient',
    'tourism.hero.main.subtitle': 'Life-Cycle Program™',
    'tourism.hero.desc': 'A regulated, data-driven international treatment ecosystem — beyond medical tourism into world-class clinical management.',
    'tourism.cta.review': 'Free Case Review',
    'tourism.cta.estimate': '48-Hour Estimate',
    'tourism.badge.tiers': '7 Service Tiers',
    'tourism.badge.phases': '5-Phase Lifecycle',
    'tourism.badge.hipaa': 'HIPAA Compliant',
    'tourism.section1.badge': 'I. Strategic Positioning',
    'tourism.section1.title': 'Our Core Philosophy',
    'tourism.section1.subtitle': 'Three pillars that define our international healthcare approach.',
    'tourism.pillar.governance': 'Clinical Governance',
    'tourism.pillar.governance.desc': 'Every procedure backed by measurable outcomes and cross-border continuity protocols.',
    'tourism.pillar.data': 'Data Integrity',
    'tourism.pillar.data.desc': 'All patient interactions logged within a secure, HIPAA-compliant lifecycle governance framework.',
    'tourism.pillar.value': 'Value Proposition',
    'tourism.pillar.value.desc': 'High-acuity medical care with the logistical precision of a global logistics firm.',
    'tourism.section2.badge': 'II. Full Tier Architecture',
    'tourism.section2.title': '7 Commercial Levels',
    'tourism.section2.subtitle': 'From remote consultations to institutional contracts — a tier for every patient profile.',
    'tourism.section3.badge': 'III. The 5-Phase Lifecycle',
    'tourism.section3.title': 'Global Patient Journey',
    'tourism.section3.subtitle': 'From initial triage to long-term continuity — every step is managed.',
    'tourism.section4.badge': 'IV. Advanced Differentiation',
    'tourism.section4.title': 'The "Complete" Layer',
    'tourism.section4.subtitle': 'What sets us apart from every other medical tourism provider.',
    'tourism.section5.badge': 'V. Revenue & Conversion',
    'tourism.section5.title': 'Conversion Engineering',
    'tourism.section5.subtitle': 'Smart tools that turn inquiries into life-saving journeys.',
    'tourism.section6.badge': 'VI. Technology & Infrastructure',
    'tourism.section6.title': 'Digital-First Healthcare',
    'tourism.section6.subtitle': 'Powered by cutting-edge technology at every touchpoint.',
    'tourism.section7.badge': 'VII. Key Performance Indicators',
    'tourism.section7.title': 'Measurable Excellence',
    'tourism.cta.final.title': 'This Is Not a Vacation',
    'tourism.cta.final.subtitle': 'With a Side of Surgery.',
    'tourism.cta.final.desc': 'It is a technologically-enabled, internationally-governed healthcare program designed for the modern global citizen.',
    'tourism.cta.final.review': 'Start Your Free Case Review',
    'tourism.cta.final.brochure': 'Download Program Brochure',

    // Partnerships
    'partnerships.hero.label': 'Global Network',
    'partnerships.hero.title': 'World-Class Partnerships',
    'partnerships.hero.subtitle': 'Connecting leading healthcare institutions across continents',
    'partnerships.stats.partners': 'Partner Institutions',
    'partnerships.stats.countries': 'Countries',
    'partnerships.stats.continents': 'Continents',
    'partnerships.areas.title': 'Partnership Areas',
    'partnerships.areas.subtitle': 'Multi-dimensional collaborations for healthcare excellence',
    'partnerships.areas.clinical': 'Clinical Excellence',
    'partnerships.areas.clinical.desc': 'Joint medical programs and specialist exchanges',
    'partnerships.areas.research': 'Research Collaboration',
    'partnerships.areas.research.desc': 'Joint research initiatives and clinical trials',
    'partnerships.areas.education': 'Education & Training',
    'partnerships.areas.education.desc': 'Medical education and professional development',
    'partnerships.areas.technology': 'Technology Transfer',
    'partnerships.areas.technology.desc': 'Access to cutting-edge medical technologies',
    'partnerships.global.title': 'Global Partners',
    'partnerships.global.subtitle': 'Trusted collaborations with world-renowned institutions',
    'partnerships.keyPartner': '★ Key Partner',

    // Research
    'research.hero.title': 'Advancing Medicine Through Innovation',
    'research.hero.subtitle': 'We are building a world-class research ecosystem, bridging the gap between clinical inquiry and patient outcomes.',
    'research.vision.title': 'Our Research Vision',
    'research.vision.p1': 'At CAPITALMED, research is the cornerstone of our quest for medical excellence. We are establishing a hub of discovery where the brightest minds collaborate to solve the most pressing healthcare challenges.',
    'research.vision.p2': 'Through strategic partnerships and state-of-the-art facilities, we are redefining the standards of medical research in the Middle East and Africa.',
    'research.areas.title': 'Priority Research Areas',
    'research.areas.oncology': 'Oncology Research',
    'research.areas.oncology.desc': 'Pioneering cancer treatment and immunotherapy studies',
    'research.areas.cardiology': 'Cardiology Studies',
    'research.areas.cardiology.desc': 'Advanced cardiovascular disease research',
    'research.areas.neuro': 'Neuroscience',
    'research.areas.neuro.desc': 'Brain disorders and neurological conditions',
    'research.areas.genomics': 'Genomics & Precision Medicine',
    'research.areas.genomics.desc': 'Personalized treatment based on genetic profiles',
    'research.areas.infectious': 'Infectious Diseases',
    'research.areas.infectious.desc': 'Emerging pathogens and vaccine development',
    'research.areas.regenerative': 'Regenerative Medicine',
    'research.areas.regenerative.desc': 'Stem cell therapy and tissue engineering',
    'research.planned': 'Planned',
    'research.ecosystem.title': 'Research Ecosystem',
    'research.ecosystem.subtitle': 'Equipping our researchers with the tools of the future.',
    'research.ecosystem.ai': 'AI-Powered Labs',
    'research.ecosystem.ai.desc': 'Machine learning integrated diagnostic and research platforms',
    'research.ecosystem.biobank': 'Bio-Bank Facility',
    'research.ecosystem.biobank.desc': 'Centralized tissue and genomic sample repository',
    'research.ecosystem.library': 'Medical Library',
    'research.ecosystem.library.desc': 'Digital and physical library with global journal access',
    'research.ecosystem.hub': 'Collaboration Hub',
    'research.ecosystem.hub.desc': 'Co-working spaces for international research teams',

    // Insurance
    'insurance.hero.label': 'Financial Transparency Promise',
    'insurance.hero.title': 'Clear Pricing, No Surprises.',
    'insurance.hero.subtitle': 'Focus on your health, we\'ll handle the rest. Our dedicated teams ensure a seamless billing experience.',
    'insurance.check': 'Check Insurance',
    'insurance.billing': 'Billing Process',
    'insurance.search.title': 'Is Your Insurance Accepted?',
    'insurance.search.subtitle': 'Search our network of 50+ local and international partners.',
    'insurance.search.placeholder': 'Search insurance provider...',
    'insurance.search.popular': 'Popular Partners: AXA, Bupa, MetLife, Allianz',
    'insurance.journey.title': 'The Transparent Billing Journey',
    'insurance.journey.subtitle': 'We believe in keeping you informed every step of the way.',
    'insurance.step1.title': 'Pre-Authorization & Estimation',
    'insurance.step1.desc': 'Before your visit, use our Cost Estimate Tool or upload your card for real-time eligibility checks.',
    'insurance.step2.title': 'In-Patient Financial Counseling',
    'insurance.step2.desc': 'Meet with a dedicated Financial Coordinator to review daily charges and deposit management.',
    'insurance.step3.title': 'Final Billing & Discharge',
    'insurance.step3.desc': 'Receive a clear, itemized digital invoice via our mobile app or email upon discharge.',
    'insurance.payment.title': 'Flexible Payment Solutions',
    'insurance.payment.subtitle': 'Multiple ways to settle your account securely and conveniently.',
    'insurance.payment.online': 'Online Payment Gateway',
    'insurance.payment.online.desc': 'Secure portal for all major credit and debit cards.',
    'insurance.payment.installment': 'Installment Plans',
    'insurance.payment.installment.desc': '0% interest installment options with partner banks for major surgeries.',
    'insurance.payment.mobile': 'Mobile Wallet',
    'insurance.payment.mobile.desc': 'Pay via Vodafone Cash, Fawry, and other e-wallets.',
    'insurance.payment.corporate': 'Corporate Billing',
    'insurance.payment.corporate.desc': 'Direct billing for corporate partners and embassies.',

    // Investment
    'investment.hero.label': 'Strategic Growth',
    'investment.hero.title': 'Invest in the Future of Healthcare',
    'investment.hero.subtitle': 'Partner with CapitalMed: The Middle East\'s First Integrated Smart Health City.',
    'investment.stats.acres': 'Total Acres',
    'investment.stats.beds': 'Total Beds',
    'investment.stats.centres': 'Specialized Centres',
    'investment.stats.theaters': 'Operative Theaters',
    'investment.opportunities.title': 'Partnership Opportunities',
    'investment.opportunities.subtitle': 'We offer flexible engagement models for global stakeholders.',
    'investment.opp.academic': 'Academic Partnership',
    'investment.opp.academic.desc': 'Collaborate on curriculum development and clinical training programs for the University Hospital.',
    'investment.opp.clinical': 'Clinical Operations',
    'investment.opp.clinical.desc': 'Operate specialized Centers of Excellence within our integrated campus ecosystem.',
    'investment.opp.rnd': 'R&D Innovation',
    'investment.opp.rnd.desc': 'Leverage our bio-bank and clinical data for pharmaceutical trials and medical device testing.',
    'investment.smart.title': 'Smart City Infrastructure',
    'investment.smart.digital': 'Integrated Digital Health',
    'investment.smart.digital.desc': 'Unified EHR connecting all institutes instantly.',
    'investment.smart.simulation': 'Simulation Center',
    'investment.smart.simulation.desc': 'Advanced training facility for complex procedures.',
    'investment.cta.title': 'Ready to Partner?',
    'investment.cta.visit': 'Schedule a Site Visit',
    'investment.cta.download': 'Download Investor Deck (PDF)',

    // Development Phases
    'dev.hero.progress': 'Phase 1 Complete',
    'dev.hero.title': 'Building the Future of Healthcare',
    'dev.hero.subtitle': 'A $1.2 Billion Vision Unfolding in Three Strategic Phases',
    'dev.stats.investment': 'Total Investment',
    'dev.stats.area': 'Square Meters',
    'dev.stats.beds': 'Hospital Beds',
    'dev.stats.completion': 'Full Completion',
    'dev.phases.title': 'Development Phases',
    'dev.phase1.title': 'Phase 1 - Foundation',
    'dev.phase1.period': '2024-2025',
    'dev.phase1.status': 'Completed',
    'dev.phase1.desc': 'University Hospital, Research Center, and core infrastructure',
    'dev.phase2.title': 'Phase 2 - Expansion',
    'dev.phase2.period': '2025-2027',
    'dev.phase2.status': 'In Progress',
    'dev.phase2.desc': 'Specialized medical institutes and additional facilities',
    'dev.phase3.title': 'Phase 3 - Completion',
    'dev.phase3.period': '2027-2030',
    'dev.phase3.status': 'Planned',
    'dev.phase3.desc': 'Full healthcare city completion with all amenities',
    'dev.milestones.title': 'Key Milestones',

    // Location
    'location.hero.label': 'Strategic Healthcare Hub',
    'location.hero.title': 'Badr City, Cairo',
    'location.hero.subtitle': 'Where Three Continents Meet for World-Class Healthcare',
    'location.stats.airport': 'from Cairo Airport',
    'location.stats.acres': 'Acres of Development',
    'location.stats.continents': 'Continents Connected',
    'location.directions': 'Get Directions',
    'location.satellite': 'Satellite View',
    'location.contact.title': 'Contact Center',
    'location.contact.hotline': 'Hotline:',
    'location.contact.international': 'International:',
    'location.hours.title': 'Visiting Hours',
    'location.hours.weekday': 'Sunday – Thursday: 9AM – 9PM',
    'location.hours.weekend': 'Friday – Saturday: 10AM – 6PM',
    'location.hours.emergency': 'Emergency: 24/7',
    'location.getting.title': 'Getting Here',
    'location.getting.subtitle': 'Multiple convenient transportation options',
    'location.transport.air': 'By Air',
    'location.transport.air.desc': 'Cairo International Airport - 35 min drive',
    'location.transport.road': 'By Road',
    'location.transport.road.desc': 'Connected to Cairo-Suez Road and Ring Road',
    'location.transport.metro': 'By Metro',
    'location.transport.metro.desc': 'Future metro connection planned (Phase 2)',
    'location.transport.bus': 'By Bus',
    'location.transport.bus.desc': 'Regular shuttle services from Cairo',
    'location.landmarks.title': 'Nearby Landmarks',
    'location.cta.title': 'Plan Your Visit',
    'location.cta.subtitle': 'Our patient services team can help with transportation, accommodation, and all your needs.',
    'location.cta.schedule': 'Schedule Visit',
    'location.cta.tourism': 'Medical Tourism',

    // News
    'news.hero.title': 'News & Resources',
    'news.hero.subtitle': 'Official updates from the CapitalMed Newsroom.',
    'news.categories.all': 'All',
    'news.categories.announcements': 'Announcements',
    'news.categories.partnerships': 'Partnerships',
    'news.categories.clinical': 'Clinical',
    'news.categories.tourism': 'Medical Tourism',
    'news.categories.community': 'Community',
    'news.readMore': 'Read More',
    'news.newsletter.title': 'Stay in the Loop',
    'news.newsletter.subtitle': 'Get the latest CapitalMed breakthroughs delivered to your inbox.',
    'news.newsletter.placeholder': 'Your email address',
    'news.newsletter.subscribe': 'Subscribe',

    // Careers
    'careers.hero.title': 'Join Our Mission',
    'careers.hero.subtitle': 'Help us shape the future of healthcare at CapitalMed. We are creating more than 15,000 jobs.',
    'careers.search.placeholder': 'Search positions...',
    'careers.filter.allDepts': 'All Departments',
    'careers.filter.medical': 'Medical',
    'careers.filter.nursing': 'Nursing',
    'careers.filter.research': 'Research',
    'careers.filter.admin': 'Administrative',
    'careers.filter.allTypes': 'All Types',
    'careers.filter.fulltime': 'Full-time',
    'careers.filter.parttime': 'Part-time',
    'careers.viewDetails': 'View Details',
    'careers.noResults': 'No positions found matching your criteria.',
    'careers.posted': 'Posted:',

    // FAQ
    'faq.hero.title': 'How can we help you today?',
    'faq.search.placeholder': 'Search questions...',
    'faq.top.title': 'Top Questions',
    'faq.help.title': 'Still Need Help?',
    'faq.help.subtitle': 'We\'re here 24/7 to assist you.',
    'faq.help.chat': 'Live Chat',
    'faq.help.chat.desc': 'Chat with our support team instantly.',
    'faq.help.chat.btn': 'Start Chat',
    'faq.help.emergency': 'Emergency Line',
    'faq.help.emergency.desc': 'Urgent medical inquiries only.',
    'faq.help.callback': 'Request Callback',
    'faq.help.callback.desc': 'We\'ll call you back within 30 mins.',
    'faq.help.callback.btn': 'Request Now',

    // Pillars
    'pillars.title': 'Three Pillars of Excellence',
    'pillars.subtitle': 'Serving patients, professionals, and partners under one integrated ecosystem',
    'pillars.patients.title': 'Patients',
    'pillars.patients.subtitle': 'Care & Booking',
    'pillars.patients.desc': 'Seamless appointment booking, telemedicine, and personalized care pathways',
    'pillars.professionals.title': 'Healthcare Professionals',
    'pillars.professionals.subtitle': 'Data & Management',
    'pillars.professionals.desc': 'Integrated clinical systems, research tools, and continuing education',
    'pillars.partners.title': 'Corporate Partners',
    'pillars.partners.subtitle': 'Investment & Operations',
    'pillars.partners.desc': 'Strategic partnerships, investment opportunities, and operational excellence',

    // CMS
    'cms.title': 'Content Management',
    'cms.edit': 'Edit',
    'cms.save': 'Save',
    'cms.cancel': 'Cancel',
    'cms.admin': 'Admin Panel',

    // Common
    'common.search': 'Search',

    // Miscs
    'misc.healthcareExcellence': 'Healthcare Excellence',
    'misc.researchInnovation': 'Research & Innovation',
    'misc.pageNotFound': 'Oops! Page not found',
    'misc.latestUpdates': 'Latest Updates',
    'misc.capitalMed': 'CapitalMed',
    'misc.capitalMedCity': 'CapitalMed Healthcare City',
    'misc.helpCenter': 'Help Center',
    'misc.expertTeam': 'Expert Medical Team',
    'misc.getInTouch': 'Get In Touch',
    'misc.joinTeam': 'Join Our Team',
    'misc.aboutCapitalMed': 'About CapitalMed',
    'map.legend': 'Legend',
    'map.bldg': 'Bldg',
    'map.contact': 'Contact',
    'map.services': 'Services',
    'map.endTour': 'End Tour',
    'map.emergency': 'Emergency',
    'map.filter': 'Filter',
    'map.virtualTour': 'Virtual Tour',
    'map.directory': 'Directory',
    'map.reset': 'Reset',
    'map.campusDirectory': 'Campus Directory',
    'map.navigatingTo': 'Navigating to',
    'map.tour': 'Tour',
    'lang.en': 'English',
    'lang.fr': 'Français',
    'lang.de': 'Deutsch',

    // Hotline
    'hotline.label': 'CAPITALMED Hotline',
    'hotline.available': 'Available 24/7 for emergencies & inquiries',

    // Success Stories
    'stories.label': 'Patient Testimonials',
    'stories.title': 'Success Stories',
    'stories.subtitle': 'Real experiences from our patients and their families',
    'stories.1.quote': 'The cardiac team at CAPITALMED saved my life. The level of care and technology here is truly world-class. From diagnosis to recovery, every step was handled with precision and compassion.',
    'stories.1.name': 'Ahmed Hassan',
    'stories.1.treatment': 'Cardiac Surgery',
    'stories.2.quote': 'Coming from Dubai for treatment was the best decision. The medical tourism team handled everything — flights, accommodation, and my entire treatment plan. I felt at home throughout.',
    'stories.2.name': 'Sarah Al-Maktoum',
    'stories.2.treatment': 'Orthopedic Surgery',
    'stories.3.quote': 'My daughter received exceptional pediatric care. The children\'s wing is designed to make young patients feel comfortable, and the doctors communicated with us every step of the way.',
    'stories.3.name': 'Fatima El-Sayed',
    'stories.3.treatment': 'Pediatric Oncology',

    // Accessibility
    'accessibility.title': 'Vision Accessibility',
    'accessibility.fontSize': 'Font Size',
    'accessibility.highContrast': 'High Contrast',
    'accessibility.highContrast.desc': 'Increase color contrast for better readability',
    'accessibility.readingMode': 'Reading Mode',
    'accessibility.readingMode.desc': 'Simplified layout for focused reading',
    'accessibility.reset': 'Reset All',

    // Patient Portal
    'portal.label': 'Your Health, Your Portal',
    'portal.title': 'Patient Portal',
    'portal.subtitle': 'Access your medical records, book appointments, and manage your healthcare journey — all in one place.',
    'portal.access.title': 'Access Your Portal',
    'portal.access.desc': 'Log in to view your health records, upcoming appointments, test results, and more.',
    'portal.login': 'Log In',
    'portal.register': 'Create Account',
    'portal.features.title': 'What You Can Do',
    'portal.features.subtitle': 'Everything you need to manage your healthcare in one place',
    'portal.feature.appointments.title': 'Book Appointments',
    'portal.feature.appointments.desc': 'Schedule and manage your visits with ease',
    'portal.feature.records.title': 'Medical Records',
    'portal.feature.records.desc': 'Access your complete health history securely',
    'portal.feature.prescriptions.title': 'Prescriptions',
    'portal.feature.prescriptions.desc': 'View and refill your medications online',
    'portal.feature.results.title': 'Test Results',
    'portal.feature.results.desc': 'Get lab and imaging results as soon as they\'re ready',
    'portal.feature.messaging.title': 'Message Your Doctor',
    'portal.feature.messaging.desc': 'Communicate directly with your care team',
    'portal.feature.billing.title': 'Billing & Payments',
    'portal.feature.billing.desc': 'View statements and make payments securely',
    'portal.feature.history.title': 'Visit History',
    'portal.feature.history.desc': 'Review past visits and treatment summaries',
    'portal.feature.insurance.title': 'Insurance Info',
    'portal.feature.insurance.desc': 'Manage your insurance details and claims',
    'portal.cta.title': 'Need Help Getting Started?',
    'portal.cta.desc': 'Our patient services team is available 24/7 to help you set up your portal account.',
    'portal.cta.contact': 'Contact Support',

    // La Plaza
    'laPlaza.badge': 'La Plaza Hospital',
    'laPlaza.tagline': 'A CAPITALMED Hospital',

    // About - Key Facts
    'about.keyFacts.title': 'CAPITALMED at a Glance',
    'about.keyFacts.landArea': 'Total Land Area',
    'about.keyFacts.builtUp': 'Total Built-Up Area',
    'about.keyFacts.jobs': 'Jobs Created',
    'about.keyFacts.patientsAnnually': 'Patients Served Annually',
    'about.keyFacts.underprivileged': 'Capacity for Underprivileged Patients',
    'about.keyFacts.greenAreas': 'Green Areas',
    'about.stat.facilities': 'Integrated Facilities',

    // About - Corporate Structure
    'about.corporate.title': 'Corporate Structure',
    'about.corporate.subtitle': 'The entities behind CAPITALMED Healthcare City',
    'about.corporate.elkalaa': 'ElKalaa Ventures',
    'about.corporate.elkalaa.desc': 'A group of industries in health, education, and investment, headed by Dr. Hassan Al-Kalla.',
    'about.corporate.ehcs': 'EHCS',
    'about.corporate.ehcs.desc': 'Egyptians for Health Care Services — the company that owns the CAPITALMED project.',
    'about.corporate.buc': 'Badr University in Cairo',
    'about.corporate.buc.desc': 'Academic partner providing medical education and research collaboration.',
    'about.corporate.cira': 'CIRA',
    'about.corporate.cira.desc': 'Cairo for Investment and Real Estate Development S.A.E.',

    // Facilities - 26 Services Mix
    'facilities.institutes.label': '26 Integrated Facilities',
    'facilities.institutes.title': 'CAPITALMED Services Mix',
    'facilities.institutes.subtitle': 'A comprehensive ecosystem of 26 fully integrated facilities, each catering to specific needs',
    'facilities.inst.universityHospital': 'University Hospital Center',
    'facilities.inst.universityHospital.desc': 'The flagship hospital with 4,000+ beds and full-spectrum medical services.',
    'facilities.inst.doctorsPlaza': "Doctors' Plaza",
    'facilities.inst.doctorsPlaza.desc': 'Outpatient clinics and specialist consultation center.',
    'facilities.inst.rehabWellness': 'Rehab & Wellness Institute',
    'facilities.inst.rehabWellness.desc': 'Physical rehabilitation and wellness programs.',
    'facilities.inst.virtualHospital': 'Virtual Hospital',
    'facilities.inst.virtualHospital.desc': 'Telemedicine and remote patient monitoring center.',
    'facilities.inst.simulationCenter': 'Simulation Center',
    'facilities.inst.simulationCenter.desc': 'Advanced training facility for complex medical procedures.',
    'facilities.inst.emergencyTrauma': 'Emergency & Trauma Institute',
    'facilities.inst.emergencyTrauma.desc': 'Level I trauma center with 24/7 emergency services.',
    'facilities.inst.orthoMusculoskeletal': 'Ortho & Musculoskeletal Institute',
    'facilities.inst.orthoMusculoskeletal.desc': 'Specialized orthopedic and musculoskeletal care.',
    'facilities.inst.cardiovascularPulmonary': 'Cardiovascular & Pulmonary Institute',
    'facilities.inst.cardiovascularPulmonary.desc': 'Heart and lung disease treatment and surgery.',
    'facilities.inst.transplant': 'Transplant Institute',
    'facilities.inst.transplant.desc': 'Organ transplant programs and post-transplant care.',
    'facilities.inst.precisionMedicine': 'Precision Medicine Institute',
    'facilities.inst.precisionMedicine.desc': 'Personalized treatment based on genetic profiles.',
    'facilities.inst.oncology': 'Oncology Institute',
    'facilities.inst.oncology.desc': 'Comprehensive cancer treatment and research center.',
    'facilities.inst.womenChildren': 'Women & Children Institute',
    'facilities.inst.womenChildren.desc': 'Maternal care, pediatrics, and neonatal services.',
    'facilities.inst.dentistryMaxillofacial': 'Dentistry & Maxillofacial Institute',
    'facilities.inst.dentistryMaxillofacial.desc': 'Dental surgery and maxillofacial reconstruction.',
    'facilities.inst.geriatric': 'Geriatric Healthcare Institute',
    'facilities.inst.geriatric.desc': 'Specialized care for elderly patients.',
    'facilities.inst.behavioralMental': 'Behavioral & Mental Health Institute',
    'facilities.inst.behavioralMental.desc': 'Psychological, psychiatric, and behavioral health services.',
    'facilities.inst.healthcareResearch': 'Healthcare Research Institute',
    'facilities.inst.healthcareResearch.desc': 'Clinical trials, medical research, and innovation.',
    'facilities.inst.assistedLiving': 'Assisted Living Care Institute',
    'facilities.inst.assistedLiving.desc': 'Long-term assisted living for patients needing ongoing support.',
    'facilities.inst.longTermCare': 'Long-term Care Institute',
    'facilities.inst.longTermCare.desc': 'Extended care programs for chronic conditions.',
    'facilities.inst.advancedNursing': 'Advanced Nursing Care Institute',
    'facilities.inst.advancedNursing.desc': 'Specialized nursing services and training programs.',
    'facilities.inst.neuroSpine': 'Neuro and Spine Institute',
    'facilities.inst.neuroSpine.desc': 'Comprehensive neurological and spinal care, surgery, and rehabilitation.',
    'facilities.inst.hrDevelopment': 'Human Resources Development Institute',
    'facilities.inst.hrDevelopment.desc': 'Training, education, and professional development for healthcare workforce.',
    'facilities.inst.centralCommand': 'Central Command Building',
    'facilities.inst.centralCommand.desc': 'Integrated operations center managing campus-wide systems and logistics.',
    'facilities.inst.hotelResidential': 'Hotel & Residential Area',
    'facilities.inst.hotelResidential.desc': 'Premium hospitality and residential accommodation for patients and families.',
    'facilities.inst.shoppingMall': 'Shopping Mall',
    'facilities.inst.shoppingMall.desc': 'Retail, dining, and lifestyle amenities for patients, visitors, and staff.',
    'facilities.inst.utilityBuildings': 'Two Central Utility Buildings',
    'facilities.inst.utilityBuildings.desc': 'Core infrastructure supporting power, water, and mechanical systems.',
    'facilities.inst.futureExpansion': 'Buildings for Future Expansion',
    'facilities.inst.futureExpansion.desc': 'Reserved space for future medical and commercial development.',

    // Healthcare Overview Page
    'healthcare.hero.label': 'Insights & Analysis',
    'healthcare.hero.title': 'Healthcare System Overview',
    'healthcare.hero.subtitle': "Understanding Egypt's healthcare landscape and how CAPITALMED is positioned to transform it",
    'healthcare.challenges.title': 'Healthcare Challenges in Egypt',
    'healthcare.challenges.subtitle': 'The quality of healthcare in Egypt varies widely and the public sector is struggling to improve access to quality services',
    'healthcare.challenge.gdp': 'Low GDP Spending',
    'healthcare.challenge.gdp.desc': 'Egypt spends only 1.5% of its GDP on healthcare while the next closest country spends 4.7% more.',
    'healthcare.challenge.nursing': 'Nursing Staff Shortage',
    'healthcare.challenge.nursing.desc': 'A clear shortage of qualified nursing staff to assist hospitals and medical centers deal with healthcare issues.',
    'healthcare.challenge.costs': 'Rising Healthcare Costs',
    'healthcare.challenge.costs.desc': "Healthcare services' increasing cost is another challenge that Egyptians suffer from.",
    'healthcare.challenge.quality': 'Quality Gap',
    'healthcare.challenge.quality.desc': 'Lack of confidence in public healthcare services forces people toward overcharging private providers.',
    'healthcare.challenge.investment': 'Investment Mismatch',
    'healthcare.challenge.investment.desc': 'Majority of investment directed toward private market — predominantly pharmacies and private clinics.',
    'healthcare.challenge.ratios': 'Bed & Nurse Ratios',
    'healthcare.challenge.ratios.desc': 'Major problems in the ratio of nurses to population and beds to population remain critical.',
    'healthcare.analysis.title': 'Strategic Analysis',
    'healthcare.analysis.desc': "Translating clients' insights and important data to achieve a concrete project. CAPITALMED will drive insights and translate them into effective action.",
    'healthcare.obj.1': 'Introduce and position CAPITALMED as an international first-of-a-kind healthcare city in the region',
    'healthcare.obj.2': 'Create strong brand awareness & recognition for the project',
    'healthcare.obj.3': 'Build a favorable perception and positive feeling around the project',
    'healthcare.obj.4': 'Raise funds by attracting qualified local and international investors',
    'healthcare.obj.5': 'Provide investment opportunities to Egyptians',
    'healthcare.diff.title': 'What Makes CAPITALMED Different',
    'healthcare.diff.1': 'Smart fully-fledged Healthcare City',
    'healthcare.diff.2': 'High-quality integrated personalized tertiary healthcare',
    'healthcare.diff.3': 'Serving more than 5 million clients annually',
    'healthcare.diff.4': '4,000+ beds, 700 ICUs, and 70 Operating Rooms',
    'healthcare.diff.5': '15,000+ multi-disciplinary healthcare providers offering ~100 specialties',
    'healthcare.diff.6': 'Highly advanced services guided by the most advanced technology',
    'healthcare.diff.7': 'Affordable highest quality services for all age groups',
    'healthcare.diff.8': 'Academic & research activities mixed with high-tech facilities',
    'healthcare.diff.9': 'Non-Medical amenities: Hotel & Hospitality, Commercial & Retail, Transport',
    'healthcare.research.label': 'Marketing Research',
    'healthcare.research.title': 'CAPITALMED Launch Research',
    'healthcare.research.subtitle': 'EHCS contracted with "Inspire" to carry out 250 one-to-one in-depth interviews with customers, doctors, and nurses from sectors A, B, & C1',
    'healthcare.areas.title': 'Areas Covered in Greater Cairo',
    'healthcare.aspirations.title': 'What Patients Aspire For',
    'healthcare.params.title': 'Parameters for Choosing a Hospital',
    'healthcare.aspire.1': 'Improving cleanliness & hygiene',
    'healthcare.aspire.2': 'Improving sterilization in hospitals',
    'healthcare.aspire.3': 'Offering more incubators',
    'healthcare.aspire.4': 'Improving emergency units',
    'healthcare.aspire.5': 'Qualified doctors, not students',
    'healthcare.aspire.6': 'Quality of operating rooms & equipment',
    'healthcare.aspire.7': 'Correct diagnosis',
    'healthcare.aspire.8': 'Blood bank availability',
    'healthcare.aspire.9': 'Post-surgery healthcare',
    'healthcare.aspire.10': 'Professional nursing training',
    'healthcare.aspire.11': 'In-hospital laboratories and radiology',
    'healthcare.findings.title': 'Key Research Findings',
    'healthcare.finding.1': 'of interviewees are no longer interested in overseas treatment',
    'healthcare.finding.2': 'believe a medical city with high caliber doctors is a good idea',
    'healthcare.finding.3': 'think CAPITALMED will improve the medical sector in Egypt',
    'healthcare.charts.title': 'Research Data & Charts',
    'healthcare.charts.subtitle': 'Detailed findings from the CAPITALMED launch research conducted across Greater Cairo',
    'healthcare.chart.problems': 'Common Problems Facing Healthcare Sector',
    'healthcare.chart.params': 'Hospital Choice Parameters',
    'healthcare.chart.priceQuality': 'Price vs Quality — Top Hospitals',
    'healthcare.chart.reception': 'Medical City Concept Reception',
    'healthcare.chart.doctorQuality': 'Doctor Qualifications Assessment',
    'healthcare.chart.bestHospital': 'Best Hospital Rankings',
    'healthcare.chart.overseas': 'Interest in Overseas Medical Care',
    'healthcare.overseas.note': 'Only 17% are willing to seek medical care abroad due to escalated prices and presence of foreign doctors in Egypt.',
    'healthcare.hospitals.title': 'Most Renowned Private Hospitals in Egypt',

    // Patient Portal - additional keys
    'portal.error.title': 'Access Denied',
    'portal.error.invalid': 'Invalid Patient ID or name. Please try again.',
    'portal.error.generic': 'Something went wrong. Please try again.',
    'portal.welcome': 'Welcome back,',
    'portal.patientId': 'Patient ID',
    'portal.logout': 'Logout',
    'portal.tab.overview': 'Overview',
    'portal.tab.appointments': 'Appointments',
    'portal.tab.doctors': 'My Doctors',
    'portal.tab.records': 'Medical Records',
    'portal.tab.results': 'Test Results',
    'portal.tab.medications': 'Medications',
    'portal.personalInfo': 'Personal Information',
    'portal.dob': 'Date of Birth',
    'portal.gender': 'Gender',
    'portal.bloodType': 'Blood Type',
    'portal.phone': 'Phone',
    'portal.email': 'Email',
    'portal.address': 'Address',
    'portal.emergency': 'Emergency Contact',
    'portal.contactName': 'Contact Name',
    'portal.contactPhone': 'Contact Phone',
    'portal.insuranceInfo': 'Insurance',
    'portal.provider': 'Provider',
    'portal.policyNumber': 'Policy Number',
    'portal.allergies': 'Allergies',
    'portal.noAllergies': 'No known allergies',
    'portal.chronic': 'Chronic Conditions',
    'portal.noChronic': 'None reported',
    'portal.currentMeds': 'Current Medications',
    'portal.noMeds': 'No current medications',
    'portal.recentActivity': 'Recent Activity',
    'portal.recordsOnFile': 'medical records on file',
    'portal.lastVisit': 'Last visit',
    'portal.upcomingAppointments': 'Upcoming Appointments',
    'portal.confirmed': 'Confirmed',
    'portal.pending': 'Pending',
    'portal.assignedDoctors': 'Assigned Doctors',
    'portal.nextVisit': 'Next Visit',
    'portal.medicalRecords': 'Medical Records',
    'portal.noRecords': 'No medical records found.',
    'portal.notes': 'Notes',
    'portal.testResults': 'Test Results',
    'portal.completed': 'Completed',
    'portal.result': 'Result',
    'portal.activePrescription': 'Active prescription',
    'portal.prescriptionHistory': 'Prescription History',
    'portal.noPrescriptions': 'No prescription records found.',
    'portal.login.desc': 'Enter your Patient ID and name to access your medical profile',
    'portal.fullName': 'Full Name',
    'portal.verifying': 'Verifying...',
    'portal.accessProfile': 'Access My Profile',
    'portal.demo': 'Demo credentials',
  },
  ar: {
    // Navigation
    'nav.home': 'الرئيسية',
    'nav.about': 'من نحن',
    'nav.services': 'الخدمات',
    'nav.doctors': 'ابحث عن طبيب',
    'nav.patients': 'المرضى',
    'nav.research': 'الأبحاث',
    'nav.contact': 'اتصل بنا',
    'nav.resources': 'الموارد',
    'nav.more': 'المزيد',
    'nav.facilities': 'المرافق',
    'nav.medicalTourism': 'السياحة العلاجية',
    'nav.partnerships': 'الشراكات',
    'nav.developmentPhases': 'مراحل التطوير',
    'nav.investment': 'الاستثمار',
    'nav.insurance': 'التأمين والفواتير',
    'nav.news': 'الأخبار',
    'nav.careers': 'الوظائف',
    'nav.location': 'الموقع',
    'nav.faq': 'الأسئلة الشائعة',
    'nav.patientPortal': 'بوابة المريض',

    // Hero
    'hero.title': 'كابيتال ميد',
    'hero.tagline': 'موثوق به مدى الحياة',
    'hero.description': 'أول مدينة طبية ذكية في مصر، تمتد على ١٤٤ فداناً في القاهرة الجديدة، تقدم التميز الطبي العالمي.',
    'hero.stats.area': '٥٧٧,٠٠٠ م²',
    'hero.stats.investment': '١.٢ مليار دولار أمريكي',
    'hero.stats.beds': '+٤,٥٠٠ سرير',
    'hero.stats.specialties': '+١٠٠ تخصص طبي',
    'hero.cta.doctor': 'ابحث عن طبيب',
    'hero.cta.learn': 'اعرف المزيد',
    'hero.smartCity': 'مدينة الرعاية الصحية الذكية',
    'hero.laPlaza': 'مستشفى لا بلازا',
    'hero.laPlaza.tagline': 'مستشفى تابع لكابيتال ميد',

    // Quick Access Bar
    'quick.bar.patients': 'المرضى',
    'quick.bar.doctors': 'الأطباء',
    'quick.bar.bookNow': 'احجز الآن',
    'quick.bar.emergency': 'الطوارئ',
    'quick.bar.hotline': 'الخط الساخن',

    // Quick Actions
    'quick.title': 'ربما تبحث عن',
    'quick.doctor': 'ابحث عن طبيب',
    'quick.doctor.desc': 'ابحث عن أخصائي',
    'quick.doctor.cta': 'ابحث الآن',
    'quick.appointments': 'حجز المواعيد',
    'quick.appointments.desc': 'احجز زيارة عبر الإنترنت',
    'quick.appointments.cta': 'احجز الآن',
    'quick.facilities': 'المرافق',
    'quick.facilities.desc': 'تصفح أقسامنا',
    'quick.facilities.cta': 'استكشف',
    'quick.specializations': 'التخصصات',
    'quick.specializations.desc': 'استكشف خبراتنا',
    'quick.specializations.cta': 'اعرف المزيد',
    'quick.tourism': 'السياحة العلاجية',
    'quick.tourism.desc': 'خطط لعلاجك في الخارج',
    'quick.tourism.cta': 'تواصل معنا',
    'quick.contact': 'اتصل بنا',

    // Stats
    'stats.patients': 'مريض سنوياً',
    'stats.beds': 'سرير في المستشفى',
    'stats.icu': 'سرير عناية مركزة',
    'stats.operating': 'غرفة عمليات',
    'stats.providers': 'مقدم رعاية صحية',
    'stats.specialties': 'تخصص طبي',

    // Services
    'services.title': 'حلولنا',
    'services.subtitle': 'خدمات رعاية صحية شاملة',
    'services.description': 'مرافق طبية حديثة بمعايير دولية',
    'services.page.title': 'خدماتنا الطبية',
    'services.page.subtitle': 'خدمات رعاية صحية عالمية مدعومة بأحدث التقنيات والرعاية الإنسانية',
    'services.learn.more': 'اعرف المزيد',
    'services.cardiology.title': 'أمراض القلب',
    'services.cardiology.desc': 'رعاية شاملة للقلب من الوقاية إلى التدخل',
    'services.neurology.title': 'الأعصاب',
    'services.neurology.desc': 'رعاية متخصصة لاضطرابات الدماغ والجهاز العصبي',
    'services.orthopedics.title': 'العظام',
    'services.orthopedics.desc': 'رعاية متقدمة للعظام والمفاصل بتقنيات طفيفة التوغل',
    'services.pediatrics.title': 'طب الأطفال',
    'services.pediatrics.desc': 'رعاية متخصصة للأطفال من جميع الأعمار',
    'services.oncology.title': 'الأورام',
    'services.oncology.desc': 'علاج السرطان المتقدم مع خطط رعاية مخصصة',
    'services.ophthalmology.title': 'طب العيون',
    'services.ophthalmology.desc': 'رعاية عيون كاملة من الفحوصات الروتينية إلى العمليات المعقدة',
    'services.internal.title': 'الباطنة',
    'services.internal.desc': 'تشخيص وعلاج شامل لأمراض البالغين',
    'services.surgery.title': 'الجراحة المتقدمة',
    'services.surgery.desc': 'إجراءات جراحية متطورة بتقنيات طفيفة التوغل',
    'services.emergency.title': 'رعاية الطوارئ على مدار الساعة',
    'services.emergency.desc': 'خدمات طوارئ على مدار الساعة مع فرق استجابة سريعة جاهزة للتعامل مع أي حالة طوارئ طبية',
    'services.emergency.24/7': 'متاح على مدار الساعة',
    'services.emergency.trauma': 'مركز إصابات المستوى الأول',
    'services.emergency.ambulance': 'أسطول إسعاف متقدم',
    'services.emergency.rapid': 'فرق استجابة سريعة',
    'services.emergency.call': 'اتصل بالطوارئ: ١٦٩٩٩',
    'services.laboratory.title': 'المختبر',
    'services.laboratory.desc': 'اختبارات تشخيصية متطورة وتحليلات دقيقة',
    'services.pharmacy.title': 'الصيدلية',
    'services.pharmacy.desc': 'خدمات صيدلية على مدار الساعة مع إدارة شاملة للأدوية',
    'services.ent.title': 'الأنف والأذن والحنجرة',
    'services.ent.desc': 'رعاية متخصصة لحالات الأنف والأذن والحنجرة',
    'services.nutrition.title': 'التغذية السريرية',
    'services.nutrition.desc': 'خطط غذائية مخصصة وعلاج تغذوي لنتائج صحية مثلى',
    'services.cta.title': 'هل تحتاج إلى مساعدة طبية؟',
    'services.cta.subtitle': 'فريقنا من الخبراء هنا لمساعدتك على مدار الساعة',
    'services.cta.appointment': 'احجز موعد',
    'services.cta.contact': 'اتصل بنا',

    // About
    'about.title': 'عن كابيتال ميد',
    'about.subtitle': 'التميز في الرعاية الصحية',
    'about.description': 'مدينة كابيتال ميد الطبية مشروع رؤيوي يمتد على ١٤٤ فداناً في مدينة بدر، القاهرة الجديدة. باستثمار إجمالي يتجاوز ١.٢ مليار دولار، تُعد أكبر مدينة طبية متكاملة في أفريقيا والشرق الأوسط، مصممة لخدمة أكثر من ٥ ملايين عميل سنوياً.',
    'about.page.title': 'من نحن',
    'about.page.subtitle': 'نحول تقديم الرعاية الصحية في مصر وأفريقيا والشرق الأوسط',
    'about.story.title': 'قصتنا',
    'about.story.p1': 'مدينة كابيتال ميد الطبية هي مشروع رؤيوي مصمم لتحويل تقديم الرعاية الصحية في مصر وأفريقيا والشرق الأوسط. تجمع مرافقنا الحديثة بين التكنولوجيا المتطورة والرعاية الإنسانية.',
    'about.story.p2': 'تقع في مدينة بدر، القاهرة الجديدة، نحن نبني نظامًا طبيًا شاملًا يضم ١٩ مرفقاً متكاملاً سيخدم ملايين المرضى سنويًا بخدمات رعاية صحية عالمية المستوى.',
    'about.years': 'سنوات من التميز',
    'about.mission': 'مهمتنا',
    'about.mission.text': 'توفير خدمات رعاية صحية عالية الجودة وسهلة الوصول تحسن الحياة وتطور العلوم الطبية في المنطقة.',
    'about.vision': 'رؤيتنا',
    'about.vision.text': 'أن نكون معروفين كوجهة إقليمية رائدة لتقديم خدمات رعاية صحية متكاملة عالمية المستوى للمجتمع الذي نخدمه بطريقة آمنة وفعالة ومحترمة محلياً ودولياً.',
    'about.values.title': 'قيمنا الأساسية',
    'about.values.subtitle': 'المبادئ التي توجه كل ما نفعله',
    'about.value.compassion': 'التعاطف',
    'about.value.excellence': 'التميز',
    'about.value.teamwork': 'العمل الجماعي',
    'about.value.integrity': 'النزاهة',
    'about.timeline.title': 'رحلتنا',
    'about.milestone.1': 'إعلان المشروع وحفل وضع حجر الأساس',
    'about.milestone.2': 'اكتمال المرحلة الأولى من البناء',
    'about.milestone.3': 'افتتاح أول جناح في المستشفى للمرضى',
    'about.milestone.4': 'التشغيل الكامل مع تفعيل جميع المرافق',
    'about.stat.area': 'متر مربع',
    'about.stat.providers': 'مقدم رعاية صحية',
    'about.stat.patients': 'مريض سنوياً',
    'about.stat.specialties': 'تخصص طبي',

    // Doctors
    'doctors.page.title': 'ابحث عن طبيب',
    'doctors.page.subtitle': 'تواصل مع نخبة من المتخصصين الطبيين',
    'doctors.search.placeholder': 'ابحث بالاسم أو التخصص...',
    'doctors.results': 'عرض {count} طبيب',
    'doctors.experience': '{years} سنة خبرة',
    'doctors.book': 'احجز',
    'doctors.no.results': 'لم يتم العثور على أطباء تطابق معاييرك',

    // Contact
    'contact.title': 'اتصل بنا',
    'contact.subtitle': 'نحن هنا للمساعدة',
    'contact.page.title': 'اتصل بنا',
    'contact.page.subtitle': 'نحن هنا للإجابة على أسئلتك وتقديم الرعاية التي تحتاجها',
    'contact.address': 'مدينة بدر، القاهرة الجديدة، مصر',
    'contact.phone': '+20 2 1234 5678',
    'contact.email': 'info@capitalmed.eg',
    'contact.hours': 'خدمات الطوارئ على مدار الساعة',
    'contact.info.address': 'العنوان',
    'contact.info.phone': 'الهاتف',
    'contact.info.email': 'البريد الإلكتروني',
    'contact.info.hours': 'ساعات العمل',
    'contact.form.title': 'أرسل لنا رسالة',
    'contact.form.name': 'الاسم الكامل',
    'contact.form.email': 'البريد الإلكتروني',
    'contact.form.phone': 'رقم الهاتف',
    'contact.form.subject': 'الموضوع',
    'contact.form.message': 'رسالتك',
    'contact.form.submit': 'إرسال الرسالة',
    'contact.form.success': 'تم إرسال الرسالة بنجاح! سنتواصل معك قريباً.',
    'contact.faq.title': 'الأسئلة الشائعة',
    'contact.faq.subtitle': 'إجابات سريعة على الأسئلة الشائعة',
    'contact.faq.q1': 'ما هي ساعات الزيارة؟',
    'contact.faq.a1': 'ساعات الزيارة العامة من ١٠:٠٠ صباحًا إلى ٨:٠٠ مساءً. ساعات زيارة العناية المركزة محدودة بأوقات معينة.',
    'contact.faq.q2': 'كيف أحجز موعد؟',
    'contact.faq.a2': 'يمكنك الحجز عبر الإنترنت من خلال موقعنا، الاتصال بنا على ١٦٩٩٩، أو زيارة مكتب الاستقبال.',
    'contact.faq.q3': 'هل تقبلون المرضى الدوليين؟',
    'contact.faq.a3': 'نعم، لدينا قسم مخصص للسياحة العلاجية لمساعدة المرضى الدوليين.',
    'contact.faq.q4': 'ما هي شركات التأمين التي تقبلونها؟',
    'contact.faq.a4': 'نقبل معظم شركات التأمين الكبرى. يرجى الاتصال بنا للحصول على معلومات محددة.',

    // Footer
    'footer.description': 'أول مدينة طبية ذكية في مصر، تمتد على ١٤٤ فداناً، تقدم خدمات طبية عالمية المستوى.',
    'footer.quicklinks': 'روابط سريعة',
    'footer.services': 'الخدمات',
    'footer.contact': 'التواصل',
    'footer.copyright': '© ٢٠٢٦ مدينة كابيتال ميد الطبية. جميع الحقوق محفوظة.',
    'footer.privacy': 'سياسة الخصوصية',
    'footer.terms': 'شروط الخدمة',

    // Facilities
    'facilities.hero.label': 'بيئة عالمية المستوى',
    'facilities.hero.title': 'ما وراء الطب',
    'facilities.hero.subtitle': 'ملاذ للشفاء، مصمم بمعايير دولية من الضيافة والراحة.',
    'facilities.hotel.label': 'ضيافة فاخرة',
    'facilities.hotel.title': 'تجربة "الفندق الطبي"',
    'facilities.hotel.desc': 'نؤمن بأن البيئة تلعب دوراً حاسماً في التعافي. تمزج منشأتنا الرعاية الطبية المتقدمة مع راحة فندق فاخر.',
    'facilities.hotel.concierge': 'خدمات الكونسيرج',
    'facilities.hotel.concierge.desc': 'مساعدة شخصية للسفر والإقامة والاحتياجات اليومية.',
    'facilities.hotel.suites': 'أجنحة تنفيذية',
    'facilities.hotel.suites.desc': 'غرف خاصة مع مناطق مخصصة للعائلة ووسائل راحة فاخرة.',
    'facilities.hotel.dining': 'مطبخ فاخر',
    'facilities.hotel.dining.desc': 'خدمة طعام في الغرفة مع قوائم أعدها أخصائيو تغذية سريرية وطهاة.',
    'facilities.retail.title': 'الممشى التجاري',
    'facilities.retail.subtitle': 'خيارات الراحة ونمط الحياة داخل الحرم',
    'facilities.retail.cafes': 'المقاهي والمطاعم',
    'facilities.retail.shops': 'المتاجر والضروريات',
    'facilities.retail.bank': 'البنوك والخدمات',
    'facilities.support.title': 'دعم الزوار والموظفين',
    'facilities.support.subtitle': 'كل ما تحتاجه لتجربة مريحة في الحرم',
    'facilities.support.parking': 'مواقف السيارات',
    'facilities.support.parking.desc': 'طابقان تحت الأرض مع أكثر من ٢٠٠٠ مكان وخدمة صف السيارات',
    'facilities.support.wifi': 'الاتصال',
    'facilities.support.wifi.desc': 'واي فاي عالي السرعة في جميع أنحاء الحرم للمرضى والزوار',
    'facilities.support.lounge': 'استراحات الموظفين',
    'facilities.support.lounge.desc': 'مناطق راحة مخصصة مع مرافق طعام للموظفين',
    'facilities.support.green': 'المساحات الخضراء',
    'facilities.support.green.desc': 'حدائق الشفاء وممرات المشي في جميع أنحاء الحرم',

    // Medical Tourism (shortened keys kept same)
    'tourism.hero.label': 'المركز العالمي',
    'tourism.hero.title': 'رعاية صحية عالمية، قريبة من المنزل',
    'tourism.hero.subtitle': 'كابيتال ميد هي "العيادة المركزية للعالم"، في متناول ٣.٦ مليار شخص خلال ٨ ساعات طيران.',
    'tourism.packages': 'عرض الباقات',
    'tourism.estimate': 'تقدير التكلفة',
    'tourism.why.title': 'لماذا مصر؟',
    'tourism.why.subtitle': 'إمكانية وصول وقيمة لا مثيل لها مقارنة بالبدائل العالمية.',
    'tourism.why.europe': 'أوروبا',
    'tourism.why.gcc': 'الخليج',
    'tourism.why.africa': 'أفريقيا',
    'tourism.why.reach': 'سكان في متناول ٨ ساعات',
    'tourism.packages.title': 'اختر مسارك',
    'tourism.packages.subtitle': 'باقات مصممة لكل حاجة',
    'tourism.package.alacarte': 'حسب الطلب',
    'tourism.package.alacarte.sub': 'المسار المرن',
    'tourism.package.alacarte.price': 'رعاية أساسية + إضافات',
    'tourism.package.doortodoor': 'من الباب إلى الباب',
    'tourism.package.doortodoor.sub': 'مسار الكونسيرج',
    'tourism.package.doortodoor.price': 'شامل فاخر',
    'tourism.popular': 'الأكثر شعبية',
    'tourism.premium.quote': 'احصل على عرض فاخر',
    'tourism.customize': 'خصص خطتك',
    'tourism.journey.title': 'رحلتك معنا',
    'tourism.journey.subtitle': 'جدول زمني سلس من الاستفسار إلى العودة الآمنة.',
    'tourism.badge.icm': 'الإدارة السريرية الدولية',
    'tourism.hero.main.title': 'برنامج المريض العالمي',
    'tourism.hero.main.subtitle': 'دورة الحياة™',
    'tourism.hero.desc': 'نظام علاجي دولي مُنظَّم وقائم على البيانات — يتجاوز السياحة العلاجية نحو إدارة سريرية عالمية المستوى.',
    'tourism.cta.review': 'مراجعة مجانية للحالة',
    'tourism.cta.estimate': 'تقدير خلال ٤٨ ساعة',
    'tourism.badge.tiers': '٧ مستويات خدمة',
    'tourism.badge.phases': 'دورة حياة من ٥ مراحل',
    'tourism.badge.hipaa': 'متوافق مع HIPAA',
    'tourism.section1.badge': 'أولاً: التموضع الاستراتيجي',
    'tourism.section1.title': 'فلسفتنا الأساسية',
    'tourism.section1.subtitle': 'ثلاث ركائز تحدد نهجنا الدولي في الرعاية الصحية.',
    'tourism.pillar.governance': 'الحوكمة السريرية',
    'tourism.pillar.governance.desc': 'كل إجراء مدعوم بنتائج قابلة للقياس وبروتوكولات استمرارية عابرة للحدود.',
    'tourism.pillar.data': 'سلامة البيانات',
    'tourism.pillar.data.desc': 'جميع تفاعلات المرضى مسجلة ضمن إطار حوكمة دورة حياة آمن ومتوافق مع HIPAA.',
    'tourism.pillar.value': 'القيمة المقترحة',
    'tourism.pillar.value.desc': 'رعاية طبية عالية الدقة مع كفاءة لوجستية على مستوى عالمي.',
    'tourism.section2.badge': 'ثانياً: هيكل المستويات الكامل',
    'tourism.section2.title': '٧ مستويات تجارية',
    'tourism.section2.subtitle': 'من الاستشارات عن بُعد إلى العقود المؤسسية — مستوى لكل ملف مريض.',
    'tourism.section3.badge': 'ثالثاً: دورة الحياة ذات الخمس مراحل',
    'tourism.section3.title': 'رحلة المريض العالمي',
    'tourism.section3.subtitle': 'من الفرز الأولي إلى الاستمرارية طويلة الأمد — كل خطوة مُدارة.',
    'tourism.section4.badge': 'رابعاً: التميز المتقدم',
    'tourism.section4.title': 'طبقة "الاكتمال"',
    'tourism.section4.subtitle': 'ما يميزنا عن كل مقدم سياحة علاجية آخر.',
    'tourism.section5.badge': 'خامساً: الإيرادات والتحويل',
    'tourism.section5.title': 'هندسة التحويل',
    'tourism.section5.subtitle': 'أدوات ذكية تحوّل الاستفسارات إلى رحلات منقذة للحياة.',
    'tourism.section6.badge': 'سادساً: التكنولوجيا والبنية التحتية',
    'tourism.section6.title': 'رعاية صحية رقمية أولاً',
    'tourism.section6.subtitle': 'مدعومة بأحدث التقنيات في كل نقطة تواصل.',
    'tourism.section7.badge': 'سابعاً: مؤشرات الأداء الرئيسية',
    'tourism.section7.title': 'تميز قابل للقياس',
    'tourism.cta.final.title': 'هذه ليست إجازة',
    'tourism.cta.final.subtitle': 'مع جراحة على الهامش.',
    'tourism.cta.final.desc': 'إنه برنامج رعاية صحية مُمكَّن تقنياً ومحكوم دولياً مصمم للمواطن العالمي الحديث.',
    'tourism.cta.final.review': 'ابدأ مراجعة حالتك المجانية',
    'tourism.cta.final.brochure': 'تحميل كتيب البرنامج',

    // Partnerships
    'partnerships.hero.label': 'شبكة عالمية',
    'partnerships.hero.title': 'شراكات عالمية المستوى',
    'partnerships.hero.subtitle': 'ربط المؤسسات الصحية الرائدة عبر القارات',
    'partnerships.stats.partners': 'مؤسسة شريكة',
    'partnerships.stats.countries': 'دول',
    'partnerships.stats.continents': 'قارات',
    'partnerships.areas.title': 'مجالات الشراكة',
    'partnerships.areas.subtitle': 'تعاون متعدد الأبعاد للتميز في الرعاية الصحية',
    'partnerships.areas.clinical': 'التميز السريري',
    'partnerships.areas.clinical.desc': 'برامج طبية مشتركة وتبادل المتخصصين',
    'partnerships.areas.research': 'التعاون البحثي',
    'partnerships.areas.research.desc': 'مبادرات بحثية مشتركة وتجارب سريرية',
    'partnerships.areas.education': 'التعليم والتدريب',
    'partnerships.areas.education.desc': 'التعليم الطبي والتطوير المهني',
    'partnerships.areas.technology': 'نقل التكنولوجيا',
    'partnerships.areas.technology.desc': 'الوصول إلى أحدث التقنيات الطبية',
    'partnerships.global.title': 'الشركاء العالميون',
    'partnerships.global.subtitle': 'تعاون موثوق مع مؤسسات عالمية مرموقة',
    'partnerships.keyPartner': '★ شريك رئيسي',

    // Research
    'research.hero.title': 'تطوير الطب من خلال الابتكار',
    'research.hero.subtitle': 'نبني نظاماً بحثياً عالمي المستوى، نسد الفجوة بين الاستقصاء السريري ونتائج المرضى.',
    'research.vision.title': 'رؤيتنا البحثية',
    'research.vision.p1': 'في كابيتال ميد، البحث هو حجر الزاوية في سعينا نحو التميز الطبي.',
    'research.vision.p2': 'من خلال الشراكات الاستراتيجية والمرافق الحديثة، نعيد تعريف معايير البحث الطبي في الشرق الأوسط وأفريقيا.',
    'research.areas.title': 'مجالات البحث ذات الأولوية',
    'research.areas.oncology': 'أبحاث الأورام',
    'research.areas.oncology.desc': 'ريادة علاج السرطان ودراسات العلاج المناعي',
    'research.areas.cardiology': 'دراسات القلب',
    'research.areas.cardiology.desc': 'أبحاث متقدمة في أمراض القلب والأوعية الدموية',
    'research.areas.neuro': 'علوم الأعصاب',
    'research.areas.neuro.desc': 'اضطرابات الدماغ والحالات العصبية',
    'research.areas.genomics': 'الجينوميات والطب الدقيق',
    'research.areas.genomics.desc': 'علاج مخصص بناءً على الملفات الجينية',
    'research.areas.infectious': 'الأمراض المعدية',
    'research.areas.infectious.desc': 'مسببات الأمراض الناشئة وتطوير اللقاحات',
    'research.areas.regenerative': 'الطب التجديدي',
    'research.areas.regenerative.desc': 'العلاج بالخلايا الجذعية وهندسة الأنسجة',
    'research.planned': 'مخطط',
    'research.ecosystem.title': 'النظام البيئي البحثي',
    'research.ecosystem.subtitle': 'تزويد باحثينا بأدوات المستقبل.',
    'research.ecosystem.ai': 'مختبرات الذكاء الاصطناعي',
    'research.ecosystem.ai.desc': 'منصات تشخيص وبحث متكاملة بالتعلم الآلي',
    'research.ecosystem.biobank': 'مرفق بنك الحيوي',
    'research.ecosystem.biobank.desc': 'مستودع مركزي لعينات الأنسجة والجينوم',
    'research.ecosystem.library': 'المكتبة الطبية',
    'research.ecosystem.library.desc': 'مكتبة رقمية ومادية مع وصول عالمي للمجلات',
    'research.ecosystem.hub': 'مركز التعاون',
    'research.ecosystem.hub.desc': 'مساحات عمل مشتركة لفرق البحث الدولية',

    // Insurance
    'insurance.hero.label': 'وعد الشفافية المالية',
    'insurance.hero.title': 'أسعار واضحة، بدون مفاجآت.',
    'insurance.hero.subtitle': 'ركز على صحتك، نحن نتولى الباقي.',
    'insurance.check': 'تحقق من التأمين',
    'insurance.billing': 'عملية الفوترة',
    'insurance.search.title': 'هل تأمينك مقبول؟',
    'insurance.search.subtitle': 'ابحث في شبكتنا من أكثر من ٥٠ شريكاً محلياً ودولياً.',
    'insurance.search.placeholder': 'ابحث عن مزود التأمين...',
    'insurance.search.popular': 'الشركاء الشائعون: أكسا، بوبا، ميتلايف، أليانز',
    'insurance.journey.title': 'رحلة الفوترة الشفافة',
    'insurance.journey.subtitle': 'نؤمن بإبقائك على اطلاع في كل خطوة.',
    'insurance.step1.title': 'التفويض المسبق والتقدير',
    'insurance.step1.desc': 'قبل زيارتك، استخدم أداة تقدير التكلفة أو حمّل بطاقتك للتحقق الفوري من الأهلية.',
    'insurance.step2.title': 'الاستشارات المالية أثناء الإقامة',
    'insurance.step2.desc': 'قابل منسقاً مالياً مخصصاً لمراجعة الرسوم اليومية وإدارة الودائع.',
    'insurance.step3.title': 'الفاتورة النهائية والخروج',
    'insurance.step3.desc': 'احصل على فاتورة رقمية مفصلة وواضحة عبر تطبيقنا أو البريد الإلكتروني عند الخروج.',
    'insurance.payment.title': 'حلول دفع مرنة',
    'insurance.payment.subtitle': 'طرق متعددة لتسوية حسابك بأمان وراحة.',
    'insurance.payment.online': 'بوابة الدفع الإلكتروني',
    'insurance.payment.online.desc': 'بوابة آمنة لجميع بطاقات الائتمان والخصم الرئيسية.',
    'insurance.payment.installment': 'خطط التقسيط',
    'insurance.payment.installment.desc': 'خيارات تقسيط بدون فوائد مع بنوك شريكة للعمليات الكبرى.',
    'insurance.payment.mobile': 'المحفظة الإلكترونية',
    'insurance.payment.mobile.desc': 'ادفع عبر فودافون كاش وفوري وغيرها.',
    'insurance.payment.corporate': 'الفوترة المؤسسية',
    'insurance.payment.corporate.desc': 'فوترة مباشرة للشركاء المؤسسيين والسفارات.',

    // Investment
    'investment.hero.label': 'النمو الاستراتيجي',
    'investment.hero.title': 'استثمر في مستقبل الرعاية الصحية',
    'investment.hero.subtitle': 'شارك مع كابيتال ميد: أول مدينة صحية ذكية متكاملة في الشرق الأوسط.',
    'investment.stats.acres': 'إجمالي الأفدنة',
    'investment.stats.beds': 'إجمالي الأسرّة',
    'investment.stats.centres': 'مركز متخصص',
    'investment.stats.theaters': 'غرفة عمليات',
    'investment.opportunities.title': 'فرص الشراكة',
    'investment.opportunities.subtitle': 'نقدم نماذج مشاركة مرنة للمستثمرين العالميين.',
    'investment.opp.academic': 'الشراكة الأكاديمية',
    'investment.opp.academic.desc': 'التعاون في تطوير المناهج وبرامج التدريب السريري للمستشفى الجامعي.',
    'investment.opp.clinical': 'العمليات السريرية',
    'investment.opp.clinical.desc': 'تشغيل مراكز تميز متخصصة ضمن نظامنا البيئي المتكامل.',
    'investment.opp.rnd': 'الابتكار والبحث والتطوير',
    'investment.opp.rnd.desc': 'الاستفادة من بنك الحيوي والبيانات السريرية للتجارب الدوائية واختبار الأجهزة الطبية.',
    'investment.smart.title': 'البنية التحتية للمدينة الذكية',
    'investment.smart.digital': 'الصحة الرقمية المتكاملة',
    'investment.smart.digital.desc': 'سجل صحي إلكتروني موحد يربط جميع المعاهد فوراً.',
    'investment.smart.simulation': 'مركز المحاكاة',
    'investment.smart.simulation.desc': 'مرفق تدريب متقدم للإجراءات المعقدة.',
    'investment.cta.title': 'هل أنت مستعد للشراكة؟',
    'investment.cta.visit': 'جدول زيارة ميدانية',
    'investment.cta.download': 'تحميل ملف المستثمرين (PDF)',

    // Development Phases
    'dev.hero.progress': 'المرحلة الأولى مكتملة',
    'dev.hero.title': 'بناء مستقبل الرعاية الصحية',
    'dev.hero.subtitle': 'رؤية بقيمة ١.٢ مليار دولار تتكشف في ثلاث مراحل استراتيجية',
    'dev.stats.investment': 'إجمالي الاستثمار',
    'dev.stats.area': 'متر مربع',
    'dev.stats.beds': 'سرير مستشفى',
    'dev.stats.completion': 'الاكتمال الكامل',
    'dev.phases.title': 'مراحل التطوير',
    'dev.phase1.title': 'المرحلة الأولى - الأساس',
    'dev.phase1.period': '٢٠٢٤-٢٠٢٥',
    'dev.phase1.status': 'مكتملة',
    'dev.phase1.desc': 'المستشفى الجامعي ومركز الأبحاث والبنية التحتية الأساسية',
    'dev.phase2.title': 'المرحلة الثانية - التوسع',
    'dev.phase2.period': '٢٠٢٥-٢٠٢٧',
    'dev.phase2.status': 'جارية',
    'dev.phase2.desc': 'معاهد طبية متخصصة ومرافق إضافية',
    'dev.phase3.title': 'المرحلة الثالثة - الاكتمال',
    'dev.phase3.period': '٢٠٢٧-٢٠٣٠',
    'dev.phase3.status': 'مخطط لها',
    'dev.phase3.desc': 'اكتمال المدينة الصحية بالكامل مع جميع المرافق',
    'dev.milestones.title': 'المعالم الرئيسية',

    // Location
    'location.hero.label': 'مركز الرعاية الصحية الاستراتيجي',
    'location.hero.title': 'مدينة بدر، القاهرة',
    'location.hero.subtitle': 'حيث تلتقي ثلاث قارات للرعاية الصحية العالمية',
    'location.stats.airport': 'من مطار القاهرة',
    'location.stats.acres': 'فدان تطوير',
    'location.stats.continents': 'قارات متصلة',
    'location.directions': 'احصل على الاتجاهات',
    'location.satellite': 'عرض القمر الصناعي',
    'location.contact.title': 'مركز الاتصال',
    'location.contact.hotline': 'الخط الساخن:',
    'location.contact.international': 'دولي:',
    'location.hours.title': 'ساعات الزيارة',
    'location.hours.weekday': 'الأحد – الخميس: ٩ صباحاً – ٩ مساءً',
    'location.hours.weekend': 'الجمعة – السبت: ١٠ صباحاً – ٦ مساءً',
    'location.hours.emergency': 'الطوارئ: ٢٤/٧',
    'location.getting.title': 'كيف تصل إلينا',
    'location.getting.subtitle': 'خيارات نقل متعددة ومريحة',
    'location.transport.air': 'جواً',
    'location.transport.air.desc': 'مطار القاهرة الدولي - ٣٥ دقيقة بالسيارة',
    'location.transport.road': 'براً',
    'location.transport.road.desc': 'متصل بطريق القاهرة-السويس والطريق الدائري',
    'location.transport.metro': 'بالمترو',
    'location.transport.metro.desc': 'اتصال مترو مخطط في المستقبل (المرحلة الثانية)',
    'location.transport.bus': 'بالحافلة',
    'location.transport.bus.desc': 'خدمات نقل منتظمة من القاهرة',
    'location.landmarks.title': 'المعالم القريبة',
    'location.cta.title': 'خطط لزيارتك',
    'location.cta.subtitle': 'فريق خدمات المرضى يمكنه المساعدة في النقل والإقامة وجميع احتياجاتك.',
    'location.cta.schedule': 'جدول زيارة',
    'location.cta.tourism': 'السياحة العلاجية',

    // News
    'news.hero.title': 'الأخبار والموارد',
    'news.hero.subtitle': 'تحديثات رسمية من غرفة أخبار كابيتال ميد.',
    'news.categories.all': 'الكل',
    'news.categories.announcements': 'إعلانات',
    'news.categories.partnerships': 'شراكات',
    'news.categories.clinical': 'سريري',
    'news.categories.tourism': 'السياحة العلاجية',
    'news.categories.community': 'المجتمع',
    'news.readMore': 'اقرأ المزيد',
    'news.newsletter.title': 'ابق على اطلاع',
    'news.newsletter.subtitle': 'احصل على أحدث إنجازات كابيتال ميد في بريدك الإلكتروني.',
    'news.newsletter.placeholder': 'بريدك الإلكتروني',
    'news.newsletter.subscribe': 'اشترك',

    // Careers
    'careers.hero.title': 'انضم إلى مهمتنا',
    'careers.hero.subtitle': 'ساعدنا في تشكيل مستقبل الرعاية الصحية في كابيتال ميد. نعمل على خلق أكثر من ١٥,٠٠٠ وظيفة.',
    'careers.search.placeholder': 'ابحث عن وظائف...',
    'careers.filter.allDepts': 'كل الأقسام',
    'careers.filter.medical': 'طبي',
    'careers.filter.nursing': 'تمريض',
    'careers.filter.research': 'أبحاث',
    'careers.filter.admin': 'إداري',
    'careers.filter.allTypes': 'كل الأنواع',
    'careers.filter.fulltime': 'دوام كامل',
    'careers.filter.parttime': 'دوام جزئي',
    'careers.viewDetails': 'عرض التفاصيل',
    'careers.noResults': 'لا توجد وظائف تطابق معاييرك.',
    'careers.posted': 'تاريخ النشر:',

    // FAQ
    'faq.hero.title': 'كيف يمكننا مساعدتك اليوم؟',
    'faq.search.placeholder': 'ابحث في الأسئلة...',
    'faq.top.title': 'أهم الأسئلة',
    'faq.help.title': 'هل ما زلت بحاجة إلى مساعدة؟',
    'faq.help.subtitle': 'نحن هنا على مدار الساعة لمساعدتك.',
    'faq.help.chat': 'الدردشة المباشرة',
    'faq.help.chat.desc': 'تحدث مع فريق الدعم فوراً.',
    'faq.help.chat.btn': 'ابدأ الدردشة',
    'faq.help.emergency': 'خط الطوارئ',
    'faq.help.emergency.desc': 'للاستفسارات الطبية العاجلة فقط.',
    'faq.help.callback': 'طلب اتصال',
    'faq.help.callback.desc': 'سنتصل بك خلال ٣٠ دقيقة.',
    'faq.help.callback.btn': 'اطلب الآن',

    // Pillars
    'pillars.title': 'ثلاث ركائز للتميز',
    'pillars.subtitle': 'خدمة المرضى والمهنيين والشركاء في نظام بيئي متكامل',
    'pillars.patients.title': 'المرضى',
    'pillars.patients.subtitle': 'الرعاية والحجز',
    'pillars.patients.desc': 'حجز مواعيد سلس، طب عن بعد، ومسارات رعاية مخصصة',
    'pillars.professionals.title': 'المتخصصون الصحيون',
    'pillars.professionals.subtitle': 'البيانات والإدارة',
    'pillars.professionals.desc': 'أنظمة سريرية متكاملة وأدوات بحثية وتعليم مستمر',
    'pillars.partners.title': 'الشركاء المؤسسيون',
    'pillars.partners.subtitle': 'الاستثمار والعمليات',
    'pillars.partners.desc': 'شراكات استراتيجية وفرص استثمارية وتميز تشغيلي',

    // CMS
    'cms.title': 'إدارة المحتوى',
    'cms.edit': 'تعديل',
    'cms.save': 'حفظ',
    'cms.cancel': 'إلغاء',
    'cms.admin': 'لوحة الإدارة',

    // Common
    'common.search': 'بحث',

    // Miscs
    'misc.healthcareExcellence': 'التميز في الرعاية الصحية',
    'misc.researchInnovation': 'البحث والابتكار',
    'misc.pageNotFound': 'عذراً! الصفحة غير موجودة',
    'misc.latestUpdates': 'أحدث التطورات',
    'misc.capitalMed': 'كابيتال ميد',
    'misc.capitalMedCity': 'مدينة كابيتال ميد الطبية',
    'misc.helpCenter': 'مركز المساعدة',
    'misc.expertTeam': 'فريق طبي خبير',
    'misc.getInTouch': 'تواصل معنا',
    'misc.joinTeam': 'انضم لفريقنا',
    'misc.aboutCapitalMed': 'عن كابيتال ميد',
    'map.legend': 'مفتاح الخريطة',
    'map.bldg': 'مبنى',
    'map.contact': 'جهة الاتصال',
    'map.services': 'الخدمات',
    'map.endTour': 'إنهاء الجولة',
    'map.emergency': 'الطوارئ',
    'map.filter': 'تصفية',
    'map.virtualTour': 'جولة افتراضية',
    'map.directory': 'الدليل',
    'map.reset': 'إعادة ضبط',
    'map.campusDirectory': 'دليل الحرم',
    'map.navigatingTo': 'التوجه إلى',
    'map.tour': 'جولة',
    'lang.en': 'الإنجليزية',
    'lang.fr': 'الفرنسية',
    'lang.de': 'الألمانية',

    // Hotline
    'hotline.label': 'الخط الساخن لكابيتال ميد',
    'hotline.available': 'متاح على مدار الساعة للطوارئ والاستفسارات',

    // Success Stories
    'stories.label': 'شهادات المرضى',
    'stories.title': 'قصص النجاح',
    'stories.subtitle': 'تجارب حقيقية من مرضانا وعائلاتهم',
    'stories.1.quote': 'فريق القلب في كابيتال ميد أنقذ حياتي. مستوى الرعاية والتكنولوجيا هنا عالمي حقاً. من التشخيص إلى التعافي، كل خطوة تمت بدقة وتعاطف.',
    'stories.1.name': 'أحمد حسن',
    'stories.1.treatment': 'جراحة القلب',
    'stories.2.quote': 'القدوم من دبي للعلاج كان أفضل قرار. فريق السياحة العلاجية تعامل مع كل شيء — الرحلات والإقامة وخطة العلاج بالكامل. شعرت وكأنني في بيتي.',
    'stories.2.name': 'سارة المكتوم',
    'stories.2.treatment': 'جراحة العظام',
    'stories.3.quote': 'حصلت ابنتي على رعاية أطفال استثنائية. جناح الأطفال مصمم ليجعل المرضى الصغار يشعرون بالراحة، والأطباء تواصلوا معنا في كل خطوة.',
    'stories.3.name': 'فاطمة السيد',
    'stories.3.treatment': 'أورام الأطفال',

    // Accessibility
    'accessibility.title': 'إمكانية الوصول البصرية',
    'accessibility.fontSize': 'حجم الخط',
    'accessibility.highContrast': 'تباين عالي',
    'accessibility.highContrast.desc': 'زيادة تباين الألوان لقراءة أفضل',
    'accessibility.readingMode': 'وضع القراءة',
    'accessibility.readingMode.desc': 'تخطيط مبسط للقراءة المركزة',
    'accessibility.reset': 'إعادة ضبط الكل',

    // Patient Portal
    'portal.label': 'صحتك، بوابتك',
    'portal.title': 'بوابة المريض',
    'portal.subtitle': 'الوصول إلى سجلاتك الطبية، حجز المواعيد، وإدارة رحلتك الصحية — كل ذلك في مكان واحد.',
    'portal.access.title': 'الوصول إلى بوابتك',
    'portal.access.desc': 'سجّل الدخول لعرض سجلاتك الصحية والمواعيد القادمة ونتائج الفحوصات والمزيد.',
    'portal.login': 'تسجيل الدخول',
    'portal.register': 'إنشاء حساب',
    'portal.features.title': 'ما يمكنك فعله',
    'portal.features.subtitle': 'كل ما تحتاجه لإدارة رعايتك الصحية في مكان واحد',
    'portal.feature.appointments.title': 'حجز المواعيد',
    'portal.feature.appointments.desc': 'جدولة وإدارة زياراتك بسهولة',
    'portal.feature.records.title': 'السجلات الطبية',
    'portal.feature.records.desc': 'الوصول إلى تاريخك الصحي الكامل بأمان',
    'portal.feature.prescriptions.title': 'الوصفات الطبية',
    'portal.feature.prescriptions.desc': 'عرض وتجديد أدويتك عبر الإنترنت',
    'portal.feature.results.title': 'نتائج الفحوصات',
    'portal.feature.results.desc': 'الحصول على نتائج المختبر والتصوير فور جاهزيتها',
    'portal.feature.messaging.title': 'مراسلة طبيبك',
    'portal.feature.messaging.desc': 'التواصل مباشرة مع فريق الرعاية',
    'portal.feature.billing.title': 'الفواتير والمدفوعات',
    'portal.feature.billing.desc': 'عرض الكشوفات وإجراء المدفوعات بأمان',
    'portal.feature.history.title': 'سجل الزيارات',
    'portal.feature.history.desc': 'مراجعة الزيارات السابقة وملخصات العلاج',
    'portal.feature.insurance.title': 'معلومات التأمين',
    'portal.feature.insurance.desc': 'إدارة تفاصيل التأمين والمطالبات',
    'portal.cta.title': 'هل تحتاج مساعدة للبدء؟',
    'portal.cta.desc': 'فريق خدمات المرضى متاح على مدار الساعة لمساعدتك في إعداد حساب بوابتك.',
    'portal.cta.contact': 'تواصل مع الدعم',

    // La Plaza
    'laPlaza.badge': 'مستشفى لا بلازا',
    'laPlaza.tagline': 'مستشفى تابع لكابيتال ميد',

    // About - Key Facts
    'about.keyFacts.title': 'كابيتال ميد في لمحة',
    'about.keyFacts.landArea': 'إجمالي مساحة الأرض',
    'about.keyFacts.builtUp': 'إجمالي المساحة المبنية',
    'about.keyFacts.jobs': 'وظيفة يتم إنشاؤها',
    'about.keyFacts.patientsAnnually': 'مريض يتم خدمتهم سنوياً',
    'about.keyFacts.underprivileged': 'سعة للمرضى المحتاجين',
    'about.keyFacts.greenAreas': 'مساحات خضراء',
    'about.stat.facilities': 'مرفق متكامل',

    // About - Corporate Structure
    'about.corporate.title': 'الهيكل المؤسسي',
    'about.corporate.subtitle': 'الكيانات وراء مدينة كابيتال ميد الطبية',
    'about.corporate.elkalaa': 'القلعة فينتشرز',
    'about.corporate.elkalaa.desc': 'مجموعة صناعات في الصحة والتعليم والاستثمار، بقيادة د. حسن القلعة.',
    'about.corporate.ehcs': 'EHCS',
    'about.corporate.ehcs.desc': 'المصريون لخدمات الرعاية الصحية — الشركة المالكة لمشروع كابيتال ميد.',
    'about.corporate.buc': 'جامعة بدر بالقاهرة',
    'about.corporate.buc.desc': 'شريك أكاديمي يوفر التعليم الطبي والتعاون البحثي.',
    'about.corporate.cira': 'سيرا',
    'about.corporate.cira.desc': 'القاهرة للاستثمار والتطوير العقاري ش.م.م.',

    // Facilities - 26 Services Mix
    'facilities.institutes.label': '٢٦ مرفقاً متكاملاً',
    'facilities.institutes.title': 'مزيج خدمات كابيتال ميد',
    'facilities.institutes.subtitle': 'نظام بيئي شامل من ٢٦ مرفقاً متكاملاً، كل منها يلبي احتياجات محددة',
    'facilities.inst.universityHospital': 'مركز المستشفى الجامعي',
    'facilities.inst.universityHospital.desc': 'المستشفى الرئيسي بأكثر من ٤٠٠٠ سرير وخدمات طبية شاملة.',
    'facilities.inst.doctorsPlaza': 'بلازا الأطباء',
    'facilities.inst.doctorsPlaza.desc': 'عيادات خارجية ومركز استشارات المتخصصين.',
    'facilities.inst.rehabWellness': 'معهد التأهيل والعافية',
    'facilities.inst.rehabWellness.desc': 'برامج التأهيل البدني والعافية.',
    'facilities.inst.virtualHospital': 'المستشفى الافتراضي',
    'facilities.inst.virtualHospital.desc': 'مركز الطب عن بعد ومراقبة المرضى عن بعد.',
    'facilities.inst.simulationCenter': 'مركز المحاكاة',
    'facilities.inst.simulationCenter.desc': 'مرفق تدريب متقدم للإجراءات الطبية المعقدة.',
    'facilities.inst.emergencyTrauma': 'معهد الطوارئ والإصابات',
    'facilities.inst.emergencyTrauma.desc': 'مركز إصابات المستوى الأول مع خدمات طوارئ على مدار الساعة.',
    'facilities.inst.orthoMusculoskeletal': 'معهد العظام والعضلات',
    'facilities.inst.orthoMusculoskeletal.desc': 'رعاية متخصصة لجراحة العظام والجهاز العضلي الهيكلي.',
    'facilities.inst.cardiovascularPulmonary': 'معهد القلب والرئة',
    'facilities.inst.cardiovascularPulmonary.desc': 'علاج وجراحة أمراض القلب والرئة.',
    'facilities.inst.transplant': 'معهد زراعة الأعضاء',
    'facilities.inst.transplant.desc': 'برامج زراعة الأعضاء ورعاية ما بعد الزراعة.',
    'facilities.inst.precisionMedicine': 'معهد الطب الدقيق',
    'facilities.inst.precisionMedicine.desc': 'علاج مخصص بناءً على الملفات الجينية.',
    'facilities.inst.oncology': 'معهد الأورام',
    'facilities.inst.oncology.desc': 'مركز شامل لعلاج السرطان والأبحاث.',
    'facilities.inst.womenChildren': 'معهد المرأة والطفل',
    'facilities.inst.womenChildren.desc': 'رعاية الأمومة وطب الأطفال وخدمات حديثي الولادة.',
    'facilities.inst.dentistryMaxillofacial': 'معهد طب الأسنان والوجه والفكين',
    'facilities.inst.dentistryMaxillofacial.desc': 'جراحة الأسنان وإعادة بناء الوجه والفكين.',
    'facilities.inst.geriatric': 'معهد رعاية المسنين',
    'facilities.inst.geriatric.desc': 'رعاية متخصصة لكبار السن.',
    'facilities.inst.behavioralMental': 'معهد الصحة النفسية والسلوكية',
    'facilities.inst.behavioralMental.desc': 'خدمات الصحة النفسية والطب النفسي والسلوكي.',
    'facilities.inst.healthcareResearch': 'معهد البحوث الصحية',
    'facilities.inst.healthcareResearch.desc': 'التجارب السريرية والبحث الطبي والابتكار.',
    'facilities.inst.assistedLiving': 'معهد الرعاية المعيشية المساعدة',
    'facilities.inst.assistedLiving.desc': 'معيشة مساعدة طويلة الأمد للمرضى الذين يحتاجون إلى دعم مستمر.',
    'facilities.inst.longTermCare': 'معهد الرعاية طويلة الأمد',
    'facilities.inst.longTermCare.desc': 'برامج رعاية ممتدة للحالات المزمنة.',
    'facilities.inst.advancedNursing': 'معهد التمريض المتقدم',
    'facilities.inst.advancedNursing.desc': 'خدمات تمريض متخصصة وبرامج تدريب.',
    'facilities.inst.neuroSpine': 'معهد الأعصاب والعمود الفقري',
    'facilities.inst.neuroSpine.desc': 'رعاية شاملة للأعصاب والعمود الفقري والجراحة والتأهيل.',
    'facilities.inst.hrDevelopment': 'معهد تنمية الموارد البشرية',
    'facilities.inst.hrDevelopment.desc': 'التدريب والتعليم والتطوير المهني للقوى العاملة الصحية.',
    'facilities.inst.centralCommand': 'مبنى القيادة المركزي',
    'facilities.inst.centralCommand.desc': 'مركز عمليات متكامل يدير أنظمة ولوجستيات الحرم بالكامل.',
    'facilities.inst.hotelResidential': 'الفندق والمنطقة السكنية',
    'facilities.inst.hotelResidential.desc': 'إقامة فندقية وسكنية متميزة للمرضى وعائلاتهم.',
    'facilities.inst.shoppingMall': 'المركز التجاري',
    'facilities.inst.shoppingMall.desc': 'مرافق تسوق وطعام وأسلوب حياة للمرضى والزوار والموظفين.',
    'facilities.inst.utilityBuildings': 'مبنيان للخدمات المركزية',
    'facilities.inst.utilityBuildings.desc': 'البنية التحتية الأساسية لدعم أنظمة الطاقة والمياه والميكانيكا.',
    'facilities.inst.futureExpansion': 'مباني للتوسع المستقبلي',
    'facilities.inst.futureExpansion.desc': 'مساحات محجوزة للتطوير الطبي والتجاري المستقبلي.',

    // Healthcare Overview Page
    'healthcare.hero.label': 'رؤى وتحليلات',
    'healthcare.hero.title': 'نظرة عامة على النظام الصحي',
    'healthcare.hero.subtitle': 'فهم المشهد الصحي في مصر وكيف تتموضع كابيتال ميد لتحويله',
    'healthcare.challenges.title': 'تحديات الرعاية الصحية في مصر',
    'healthcare.challenges.subtitle': 'تتفاوت جودة الرعاية الصحية في مصر بشكل كبير ويكافح القطاع العام لتحسين الوصول إلى خدمات عالية الجودة',
    'healthcare.challenge.gdp': 'انخفاض إنفاق الناتج المحلي',
    'healthcare.challenge.gdp.desc': 'تنفق مصر ١.٥٪ فقط من ناتجها المحلي الإجمالي على الرعاية الصحية بينما أقرب دولة تنفق ٤.٧٪ أكثر.',
    'healthcare.challenge.nursing': 'نقص طاقم التمريض',
    'healthcare.challenge.nursing.desc': 'نقص واضح في طاقم التمريض المؤهل لمساعدة المستشفيات والمراكز الطبية.',
    'healthcare.challenge.costs': 'ارتفاع تكاليف الرعاية الصحية',
    'healthcare.challenge.costs.desc': 'ارتفاع تكلفة خدمات الرعاية الصحية هو تحدٍ آخر يعاني منه المصريون.',
    'healthcare.challenge.quality': 'فجوة الجودة',
    'healthcare.challenge.quality.desc': 'انعدام الثقة في خدمات الرعاية الصحية العامة يدفع الناس نحو مقدمي الخدمات الخاصة المكلفين.',
    'healthcare.challenge.investment': 'عدم توازن الاستثمار',
    'healthcare.challenge.investment.desc': 'غالبية الاستثمار موجهة نحو السوق الخاص — خاصة الصيدليات والعيادات الخاصة.',
    'healthcare.challenge.ratios': 'نسب الأسرّة والتمريض',
    'healthcare.challenge.ratios.desc': 'مشاكل كبيرة في نسبة الممرضات إلى السكان والأسرّة إلى السكان لا تزال حرجة.',
    'healthcare.analysis.title': 'التحليل الاستراتيجي',
    'healthcare.analysis.desc': 'ترجمة رؤى العملاء والبيانات المهمة لتحقيق مشروع متين. كابيتال ميد ستقود الرؤى وتترجمها إلى عمل فعّال.',
    'healthcare.obj.1': 'تقديم كابيتال ميد كأول مدينة صحية دولية فريدة في المنطقة',
    'healthcare.obj.2': 'خلق وعي قوي بالعلامة التجارية والاعتراف بالمشروع',
    'healthcare.obj.3': 'بناء تصور إيجابي وشعور جيد حول المشروع',
    'healthcare.obj.4': 'جمع الأموال من خلال جذب مستثمرين محليين ودوليين مؤهلين',
    'healthcare.obj.5': 'توفير فرص استثمارية للمصريين',
    'healthcare.diff.title': 'ما الذي يميز كابيتال ميد',
    'healthcare.diff.1': 'مدينة صحية ذكية متكاملة',
    'healthcare.diff.2': 'رعاية صحية ثلاثية متكاملة وشخصية عالية الجودة',
    'healthcare.diff.3': 'خدمة أكثر من ٥ ملايين عميل سنوياً',
    'healthcare.diff.4': 'أكثر من ٤٠٠٠ سرير و٧٠٠ عناية مركزة و٧٠ غرفة عمليات',
    'healthcare.diff.5': 'أكثر من ١٥,٠٠٠ مقدم رعاية صحية متعدد التخصصات يقدمون ~١٠٠ تخصص',
    'healthcare.diff.6': 'خدمات متقدمة للغاية موجهة بأحدث التقنيات',
    'healthcare.diff.7': 'أعلى جودة بأسعار معقولة لجميع الفئات العمرية',
    'healthcare.diff.8': 'أنشطة أكاديمية وبحثية ممزوجة بمرافق عالية التقنية',
    'healthcare.diff.9': 'مرافق غير طبية: فنادق وضيافة ومرافق تجارية ونقل',
    'healthcare.research.label': 'البحث التسويقي',
    'healthcare.research.title': 'بحث إطلاق كابيتال ميد',
    'healthcare.research.subtitle': 'تعاقدت EHCS مع "إنسباير" لإجراء ٢٥٠ مقابلة فردية معمقة مع العملاء والأطباء والممرضين من القطاعات A وB وC1',
    'healthcare.areas.title': 'المناطق المشمولة في القاهرة الكبرى',
    'healthcare.aspirations.title': 'ما يطمح إليه المرضى',
    'healthcare.params.title': 'معايير اختيار المستشفى',
    'healthcare.aspire.1': 'تحسين النظافة والتعقيم',
    'healthcare.aspire.2': 'تحسين التعقيم في المستشفيات',
    'healthcare.aspire.3': 'توفير المزيد من الحاضنات',
    'healthcare.aspire.4': 'تحسين وحدات الطوارئ',
    'healthcare.aspire.5': 'أطباء مؤهلون وليس طلاب',
    'healthcare.aspire.6': 'جودة غرف العمليات والمعدات',
    'healthcare.aspire.7': 'التشخيص الصحيح',
    'healthcare.aspire.8': 'توفر بنك الدم',
    'healthcare.aspire.9': 'رعاية ما بعد الجراحة',
    'healthcare.aspire.10': 'تدريب تمريضي مهني',
    'healthcare.aspire.11': 'مختبرات وأشعة داخل المستشفيات',
    'healthcare.findings.title': 'نتائج البحث الرئيسية',
    'healthcare.finding.1': 'من المستجوبين لم يعودوا مهتمين بالعلاج في الخارج',
    'healthcare.finding.2': 'يعتقدون أن مدينة طبية بأطباء عاليي الكفاءة فكرة جيدة',
    'healthcare.finding.3': 'يعتقدون أن كابيتال ميد ستحسن القطاع الطبي في مصر',
    'healthcare.charts.title': 'بيانات ورسوم البحث',
    'healthcare.charts.subtitle': 'نتائج مفصلة من بحث إطلاق كابيتال ميد في القاهرة الكبرى',
    'healthcare.chart.problems': 'المشاكل الشائعة في قطاع الرعاية الصحية',
    'healthcare.chart.params': 'معايير اختيار المستشفى',
    'healthcare.chart.priceQuality': 'السعر مقابل الجودة — أفضل المستشفيات',
    'healthcare.chart.reception': 'استقبال مفهوم المدينة الطبية',
    'healthcare.chart.doctorQuality': 'تقييم مؤهلات الأطباء',
    'healthcare.chart.bestHospital': 'ترتيب أفضل المستشفيات',
    'healthcare.chart.overseas': 'الاهتمام بالرعاية الطبية في الخارج',
    'healthcare.overseas.note': 'فقط ١٧٪ مستعدون للعلاج في الخارج بسبب ارتفاع الأسعار ووجود أطباء أجانب في مصر.',
    'healthcare.hospitals.title': 'أشهر المستشفيات الخاصة في مصر',

    // Patient Portal - additional keys
    'portal.error.title': 'تم رفض الوصول',
    'portal.error.invalid': 'رقم المريض أو الاسم غير صحيح. حاول مرة أخرى.',
    'portal.error.generic': 'حدث خطأ. حاول مرة أخرى.',
    'portal.welcome': 'مرحباً بعودتك،',
    'portal.patientId': 'رقم المريض',
    'portal.logout': 'تسجيل الخروج',
    'portal.tab.overview': 'نظرة عامة',
    'portal.tab.appointments': 'المواعيد',
    'portal.tab.doctors': 'أطبائي',
    'portal.tab.records': 'السجلات الطبية',
    'portal.tab.results': 'نتائج الفحوصات',
    'portal.tab.medications': 'الأدوية',
    'portal.personalInfo': 'المعلومات الشخصية',
    'portal.dob': 'تاريخ الميلاد',
    'portal.gender': 'الجنس',
    'portal.bloodType': 'فصيلة الدم',
    'portal.phone': 'الهاتف',
    'portal.email': 'البريد الإلكتروني',
    'portal.address': 'العنوان',
    'portal.emergency': 'جهة اتصال الطوارئ',
    'portal.contactName': 'اسم جهة الاتصال',
    'portal.contactPhone': 'هاتف جهة الاتصال',
    'portal.insuranceInfo': 'التأمين',
    'portal.provider': 'مقدم الخدمة',
    'portal.policyNumber': 'رقم الوثيقة',
    'portal.allergies': 'الحساسية',
    'portal.noAllergies': 'لا حساسية معروفة',
    'portal.chronic': 'الأمراض المزمنة',
    'portal.noChronic': 'لا يوجد',
    'portal.currentMeds': 'الأدوية الحالية',
    'portal.noMeds': 'لا أدوية حالية',
    'portal.recentActivity': 'النشاط الأخير',
    'portal.recordsOnFile': 'سجل طبي محفوظ',
    'portal.lastVisit': 'آخر زيارة',
    'portal.upcomingAppointments': 'المواعيد القادمة',
    'portal.confirmed': 'مؤكد',
    'portal.pending': 'قيد الانتظار',
    'portal.assignedDoctors': 'الأطباء المعالجون',
    'portal.nextVisit': 'الزيارة القادمة',
    'portal.medicalRecords': 'السجلات الطبية',
    'portal.noRecords': 'لا توجد سجلات طبية.',
    'portal.notes': 'ملاحظات',
    'portal.testResults': 'نتائج الفحوصات',
    'portal.completed': 'مكتمل',
    'portal.result': 'النتيجة',
    'portal.activePrescription': 'وصفة طبية نشطة',
    'portal.prescriptionHistory': 'سجل الوصفات الطبية',
    'portal.noPrescriptions': 'لا توجد سجلات وصفات طبية.',
    'portal.login.desc': 'أدخل رقم المريض واسمك للوصول إلى ملفك الطبي',
    'portal.fullName': 'الاسم الكامل',
    'portal.verifying': 'جارٍ التحقق...',
    'portal.accessProfile': 'الوصول إلى ملفي',
    'portal.demo': 'بيانات تجريبية',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Detect region for default language
const detectDefaultLanguage = (): Language => {
  const saved = localStorage.getItem('language') as Language;
  if (saved === 'ar' || saved === 'en') return saved;
  
  // Try to detect based on timezone/locale
  try {
    const timezone = Intl.DateTimeFormat().resolvedOptions().timeZone;
    const locale = navigator.language || '';
    
    // Arabic-speaking regions: Egypt, North Africa
    const arabicTimezones = ['Africa/Cairo', 'Africa/Tripoli', 'Africa/Tunis', 'Africa/Algiers', 'Africa/Casablanca'];
    if (arabicTimezones.some(tz => timezone.includes(tz))) return 'ar';
    if (locale.startsWith('ar')) return 'ar';
  } catch {
    // fallback
  }
  
  return 'en';
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(detectDefaultLanguage);

  const isRTL = language === 'ar';

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language, isRTL]);

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
  }, []);

  const t = useCallback((key: string): string => {
    return translations[language][key] || key;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
